### ISSUE TITLE
Wrong order of top navigation pane

### ISSUE THREAD

**Issue by tiev** [thoughtworks/build-your-own-radar#1]
Quadrant labels on top navigation pane do not follow the order in Google Sheet

**Comment by arunvelsriram** [comment]
Hi @tiev,
Thank you for bringing this up.

This issue is known from our side. We are planning to fix this in our upcoming releases but meanwhile if you have a fix already feel free to raise a Pull Request to us.

Thanks,
@arunvelsriram / @vaishnavi-prabakar

**Comment by tiev** [comment]
Hi @arunvelsriram,

Seems that the buttons are intentionally ordered to quadrants by clockwise rotation.
```js
    _.each([0, 3, 2, 1], function (i) {
      addButton(quadrants[i]);
    });
```
By the way, quadrants are drawn counter-clockwise.

So should we fix the drawing to make quadrants clockwise or just fix the buttons only?
I preferred to fix only the buttons, then the fix is very small.

Regards,
Viet

**Comment by Rajik** [comment]
Hi @tiev,
We have now fixed this issue in our latest release.
The buttons now will be in counter-clockwise direction w.r.t the order of the quadrants.
Closing this issue now!

Thanks.

**Comment by tiev** [comment]
Thanks
