### ISSUE TITLE
How to configure techradar for prod environment?

### ISSUE THREAD

**Issue by bharathnatarajan1** [thoughtworks/build-your-own-radar#100]
What are the steps to be followed to configure and run tech radar for prod environment and as a background service?

**Comment by marisahoenig** [comment]
Hi @bharathnatarajan1 — if this is still an issue, can you provide more context? If the instructions are not in the README, we likely don't have instructions to match your scenario. Closing this as stale but feel free to reopen if you need support. Thanks!
