### ISSUE TITLE
Data not loading when running local

### ISSUE THREAD

**Issue by ckerwer** [thoughtworks/build-your-own-radar#11]
I clone the repository, did npm install and startet with npm run dev.

When building a radar by URL (my own or your example "https://docs.google.com/spreadsheets/d/1waDG0_W3-yNiAaUfxcZhTKvl7AUCgXwQw8mdPjCz86U/edit")
it always ends in "Oops! It seems like there are some problems with loading your data. ...".

With the hosted version https://radar.thoughtworks.com everything works fine, even with my own google sheets.

**Comment by jac121212** [comment]
I get this to.
My radar is hosted on a linux (CentOS 7) Vagrant box. 
The Google Sheet works fine on https://radar.thoughtworks.com but fails to load from my localhost:8080 front page.

**Comment by NivedhaSenthil** [comment]
This issue was due to update in a library Tabletop. Fixed by updating the column_name variable used.
