### ISSUE TITLE
Is it possible to use JSON object as a datasource for tech radar?

### ISSUE THREAD

**Issue by bharathnatarajan1** [thoughtworks/build-your-own-radar#112]
We have hosted tech radar internally and have planned to use Mongo DB as our datasource for techradar. We have developed an api which exposes the data required for techradar as JSON Object as shown below.

What would be steps required to enable techradar to consume data in JSON object below instead of .csv format?

**JSON Object:**
_[{"_id":"5cf8f2faba9e7813d0ff4b00","name":"name","ring":"ring","quadrant":"quadrant","isnew":"isNew","description":"description"},{"_id":"5cf8f47de5664f3fc40b52a1","name":"Ansible Tower","ring":"adopt","quadrant":"tools","isNew":"TRUE","description":"Ansible Tower is a configuration management and automation tool that is used as a part of the DWS Tooling solution.<strong>More information on usage can be found on the</strong> <a href='https://confluence.net/display/SOP+-+Products+-+Ansible+Tower'>confluence guide.</a>.","isnew":"TRUE"},{"_id":"5cf90820ba9e7813d0ff4b02","name":"Ansible Broker","ring":"assess","quadrant":"languages & frameworks","isNew":"TRUE","description":"The Ansible Broker provides a generic way to execute approved playbooks in Public Cloud through EUROPA Corenet Ansible Tower clusters.<strong>DWS client has been enhanced to perform calls to the Ansible Broker to perform operations required as part of SDP.</strong> More information can be found at <a href='https://confluence.net/display/Ansible+Broker'>confluence guide</a>.","isnew":"TRUE"},{"_id":"5cf908f1ba9e7813d0ff4b03","name":"AppDynamics","ring":"hold","quadrant":"platforms","isNew":"FALSE","description":"AppDynamics Application Performance Management (APM) provides end-to-end business transaction-centric management of most complex and distributed applications. Auto-discovered transactions, dynamic baselining, code-level diagnostics, and Virtual War Room collaboration ensure rapid issue identification and resolution to maintain an ideal user experience. More information about AppDynamics <a href='https://confluence.net/display/AE+-+Generic+-+Monitoring+-+AppDynamics'>AppDynamics Confluence Guide</a>.","isnew":"FALSE"},{"_id":"5cf90988ba9e7813d0ff4b04","name":"Apache Kafka","ring":"trial","quadrant":"techniques","isNew":"FALSE","description":"Apache Kafka for high-ingress data streams and replay Apache Kafka, build applications that process and re-process streamed data on disk. More information about Apache Kafka can be found at <a href='https://confluence.net/display/Apache+Kafka'>kafka confluence guide</a>.","isnew":"FALSE"}]_

**Comment by setchy** [comment]
@Vaishnavij - I believe this issue can now be closed

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now
