### ISSUE TITLE
Is this project working?

### ISSUE THREAD

**Issue by gsolaiappan** [thoughtworks/build-your-own-radar#114]
Hi,

Can some on help?

When I tried to use the shared sheet on the localhost:8080, I'm receiving an error and below is the 
log from the Developer console.

npm run dev was successful and I was able to see the Initial page loaded properly, when I provide the sheet link, It is not building the radar.

I used the following sheet:
==

https://docs.google.com/spreadsheets/d/1vmXx5CFxek3UUgJ-2WnYJC8tpLBvcBuz9ylFjyN0qQA/edit#gid=1375641181

====

factory.js:241 undefined
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
sheet.js:34 GET https://sheets.googleapis.com/v4/spreadsheets/1vmXx5CFxek3UUgJ-2WnYJC8tpLBvcBuz9ylFjyN0qQA?key=undefined 400
Sheet.self.validate @ sheet.js:34
GoogleSheet.self.build @ factory.js:95
GoogleSheetInput.self.build @ factory.js:242
eval @ site.js:9
./src/site.js @ main.ce300904729889846ca5.js:12925
__webpack_require__ @ main.ce300904729889846ca5.js:20
eval @ client:2
0 @ main.ce300904729889846ca5.js:13035
__webpack_require__ @ main.ce300904729889846ca5.js:20
(anonymous) @ main.ce300904729889846ca5.js:84
(anonymous) @ main.ce300904729889846ca5.js:87
cb=gapi.loaded_0:113 client_id and scope must both be provided to initialize OAuth.
cb=gapi.loaded_0:151 Uncaught TypeError: Cannot read property 'isSignedIn' of null
    at Object.GoogleAuth.self.login (googleAuth.js:108)
    at Object.eval [as loadedCallback] (factory.js:153)
    at eval (googleAuth.js:78)
    at h.uJ (cb=gapi.loaded_0:163)
    at xs (cb=gapi.loaded_0:166)
    at Wq (cb=gapi.loaded_0:166)
    at _.C.uea (cb=gapi.loaded_0:166)
    at Ap (cb=gapi.loaded_0:157)
GoogleAuth.self.login @ googleAuth.js:108
eval @ factory.js:153
eval @ googleAuth.js:78
h.uJ @ cb=gapi.loaded_0:163
xs @ cb=gapi.loaded_0:166
Wq @ cb=gapi.loaded_0:166
_.C.uea @ cb=gapi.loaded_0:166
Ap @ cb=gapi.loaded_0:157
setTimeout (async)
tp @ cb=gapi.loaded_0:151
(anonymous) @ cb=gapi.loaded_0:166
Ap @ cb=gapi.loaded_0:157
Promise.then (async)
um @ cb=gapi.loaded_0:157
_.Qp @ cb=gapi.loaded_0:157
er @ cb=gapi.loaded_0:165
_.C.fl @ cb=gapi.loaded_0:164
(anonymous) @ cb=gapi.loaded_0:159
g @ cb=gapi.loaded_0:815
(anonymous) @ cb=gapi.loaded_0:814
(anonymous) @ cb=gapi.loaded_0:430
E.__cb @ cb=gapi.loaded_0:364
g @ cb=gapi.loaded_0:357
c @ cb=gapi.loaded_0:352

**Comment by mrcehlo** [comment]
I've played around a little bit with this tool and it worked as follows:
- dockerised version: [(link)](https://hub.docker.com/r/wwwthoughtworks/build-your-own-radar/) everything worked fine
- clone from master of this repo: rendering only sheets published as CSV format, otherwise it fails under "not authorized" despite of publishing it as "public"

Sorry not being able to help you further, but a shortcut would be trying the docker version

**Comment by gsolaiappan** [comment]
Thank you Marcelo, Will try that.

**Comment by SARAN-thala** [comment]
I'm closing this issue now, please feel free to open if you have any.
