### ISSUE TITLE
Is this repo still live?

### ISSUE THREAD

**Issue by jean** [thoughtworks/build-your-own-radar#119]
@SARAN-thala sorry to bug you, but it looks like you're the last person to work on this repo.
Is it still a live project at ThoughtWorks? There are many issues and PRs going back some years.

It looks like https://github.com/raiffeisensoftware/build-your-own-radar is quite a lively fork. Maybe they could be split off so that we could log issues and PRs against them. I can't seem to mention @ChristophRSG though (no autocomplete in GitHub). 

Does anyone know of any other candidate fork?

**Comment by ChristophRSG** [comment]
Hi @jean ,

I'm a developer at [Raiffeisen Software GmbH](https://www.r-software.at/), where this fork you mentioned is from.

We heavily adapted the fork to our needs and added some cool stuff (e.g. jump to the entry on blip click, ability to use a JSON config, ...) but also removed some we currently don't need (e.g. the Google Sheets ability).
In addition, we updated the dependencies and updated the code to ES6.
We are happy you found the fork and if you want to log issues or open PRs, go ahead! :)

**Comment by jean** [comment]
Hi @ChristophRSG , thanks for the response :smile: 

I would certainly miss the Google Sheets ability, it provides a very easy way to introduce the Radar in an organization which doesn't already have a process in place to track technologies. 

If we do adopt it, we would not stick with Google Sheets in the longer term though. 
And I would certainly like to log issues if I get the chance, but your fork doesn't have a tracker.
I think it's because it's a fork, and GitHub wants to push issues to the upstream tracker? I'm not sure though.
This [stackoverflow answer](https://stackoverflow.com/a/16052845/274318) suggests contacting GitHub support to split off your repo. 

![Screenshot_20191129-162917_Brave](https://user-images.githubusercontent.com/84800/69858820-67f22080-12c5-11ea-88ab-076572d5c282.jpg)

**Comment by SARAN-thala** [comment]
Hi @jean ,

Yes, it is still a live project in ThoughtWorks. 

Given other priorities recently, we were not able to focus on pull requests and issues. We make sure we will review the PRs and update the status going forward.

Please let us know if you have any specific requests or issue. so that we can prioritise it.

Thanks,
The BYOR Team

**Comment by jean** [comment]
@SARAN-thala awesome, that's good to hear. I don't have any immediate issue, but I want to promote this tool within my company. As such, I want to have an answer if people push back pointing at the many open PRs.

**Comment by ChristophRSG** [comment]
@jean I activated the Issue tab in the project, so you are also welcome to open issues there :)

**Comment by SARAN-thala** [comment]
I'm going to close this issue. Please feel free to open if you have any.
