### ISSUE TITLE
BYOR styles aren't working 

### ISSUE THREAD

**Issue by tharangahewa** [thoughtworks/build-your-own-radar#120]
Dear all,

As at this moment, BYOR is looking ugly, and it seems like it is missing a style sheet.
https://www.thoughtworks.com/css/screen.css

Hope this is the correct place to raise this kind of issue. If not my apologies.

![Screen Shot 2019-12-03 at 8 24 23 AM](https://user-images.githubusercontent.com/38223834/70016477-6f0b7e00-15a6-11ea-9515-e536e9b440aa.png)

**Comment by SARAN-thala** [comment]
Thanks for letting us know @tharangahewa . We are looking into this issue and try to resolve ASAP.

**Comment by SARAN-thala** [comment]
We deployed with this PR, Now you can see the style sheets loading properly.
Closing this issue now.
Please feel free to open if you have the same issue.

Thanks
