### ISSUE TITLE
target attributes stripped from a tags in descriptions

### ISSUE THREAD

**Issue by eudaimos** [thoughtworks/build-your-own-radar#128]
When I include a `target="_blank"` in the anchor tags within my descriptions, these are being stripped out in the end product (referring to the one in use at radar.thoughtworks.com).

After generating the radar, when I inspect a link using Chrome Dev Tools, I can clearly see the `target` attribute is gone and only the `href` remains.

Is there a reason this is being done?

My goal is to allow links to the reference URLs for blips in the descriptions to not navigate away from the Radar but to open up a new window or tab for the viewer.

**Comment by SARAN-thala** [comment]
Hi @eudaimos ,

We are looking into this issue. We'll get back to you shortly.

Thanks

**Comment by scramboy** [comment]
Hi @SARAN-thala, would it be the [sanitize-html](https://github.com/punkave/sanitize-html) being too strict?

Also, would it make sense to add `<base target="_blank">` in the header? Once a user is taken away by clicking on a link (in blip description), going back might need reloading of the main js, which is 2M+.

**Comment by npfisterIT** [comment]
Hi, @SARAN-thala any update to this issue? Current build will still strip `target="_blank"` and `rel="noreferrer"` from anchors.

**Comment by yashanandan** [comment]
Hi @npfisterIT, this has been fixed in the latest code changes, we will post a docker build soon with other fixes
