### ISSUE TITLE
Project seems to phone home / require a thoughtworks.com css file

### ISSUE THREAD

**Issue by DovOps** [thoughtworks/build-your-own-radar#144]
Is this line intentional?  Is there a reason this wouldn't be included as source in the repo, but instead be referenced externally?

 
https://github.com/thoughtworks/build-your-own-radar/blob/1e01993d3acc1360ce4ff2b85b641f02cbf0c039/src/stylesheets/base.scss#L8

**Comment by arunvelsriram** [comment]
This is intriguing. Could we please explain rationale behind this if its intentional?

Also the URL is leaking infrastructure details to the world.

**Comment by trentj-woodside** [comment]
Yeah, it'd be great to get rid of this.

**Comment by marisahoenig** [comment]
Hi @DovOps — I'm not sure _when_ it was removed, but it looks like this is no longer in the repo. Thanks for calling it out.
Cheers,
Marisa
