### ISSUE TITLE
Blips are overlapping with the white lines seperating quadrants

### ISSUE THREAD

**Issue by Hiranmuduganti** [thoughtworks/build-your-own-radar#146]
In current radar 51 and 74 are overlaping over whiteline between quadrants

**Comment by SARAN-thala** [comment]
Hi @Hiranmuduganti Could you explain more about this issue?

**Comment by marisahoenig** [comment]
Hi @Hiranmuduganti — this design issue should be fixed with the new design refresh. Feel free to reopen if you're still experiencing issues.
