### ISSUE TITLE
Only 1 Quadrant displaying

### ISSUE THREAD

**Issue by parthparulekar** [thoughtworks/build-your-own-radar#149]
I am experiencing an issue when loading the radar. It occasionally only displays the top-right quadrant. I did not change any of the radar building code, it is all ThoughtWorks' code on the radar-building functionality. I only edited surrounding UI.

**Comment by Rajik** [comment]
Can you please give us more details to debug?

**Comment by marisahoenig** [comment]
@parthparulekar Are you still experiencing this issue and have additional details? Closing for now but please reopen if you're still having issues. Cheers!
