### ISSUE TITLE
when I add console.log statements into the source code, nothing is writing out to the terminal

### ISSUE THREAD

**Issue by andy9876** [thoughtworks/build-your-own-radar#15]
Are there environment settings that need to be changed in webpack.config.js?

**Comment by pamo** [comment]
Are you looking in your terminal or in your browser dev tools console?

**Comment by andy9876** [comment]
I am looking in my terminal where I issued the npm run dev command

Thanks,
Andy

**Comment by andy9876** [comment]
wow I am an idiot.  did not think to look at the browser dev tools console.
I see my logs in there.

Thanks,
Andy
