### ISSUE TITLE
How to implement Google Authorization

### ISSUE THREAD

**Issue by parthparulekar** [thoughtworks/build-your-own-radar#150]
I have seen a PR from #62 regarding implementing Google OAuth 2.0. I was invested in that, and I believe this clashed with the previous non-functional Google OAuth 2.0 implementation that came with the original BYOR repo. 

#62 uses the env variable USE_AUTHENTICATION.

Originally, ThoughtWorks used a SKIP_GOOGLE_AUTH env variable. Re-visiting the README today I saw the mention of an ENABLE_GOOGLE_AUTH env variable. 

My question is, can I use Google Authentication with the current state of the ThoughtWorks BYOR without additional code? 

Additionally, where should the following be included in my code to use google authentication? 
```
export ENABLE_GOOGLE_AUTH=true
export API_KEY=[Google API Key]
export CLIENT_ID=[Google Client ID]
```
Do we not need login.js or profileMenu.js files?

**Comment by ar000n** [comment]
Hi @parthparulekar 

We have an updated README. If you want to use Google Authentication, set these environment variables
`export ENABLE_GOOGLE_AUTH=true
export API_KEY=[Google API Key]
export CLIENT_ID=[Google Client ID]`

**Comment by parthparulekar** [comment]
Thanks @ar000n, I understand that part. I need to create those environment variables but also add those export lines somewhere. Which file should the follow be included in?
```
export ENABLE_GOOGLE_AUTH=true
export API_KEY=[Google API Key]
export CLIENT_ID=[Google Client ID]
```

The reason I simply cannot set environment variables and must use "export" 3 times is explained here as well: https://stackoverflow.com/questions/44915758/node-process-env-variable-name-returning-undefined

Where should those lines go?

**Comment by BrunnerLivio** [comment]
@paolocarrasco You need to build this repository & add those environment variables:

(this code is for *NIX based systems, but should be easy to rewrite this in PowerShell)

```bash
git clone <this_repo_or_your_fork>
cd build-your-own-radar
npm i
export ENABLE_GOOGLE_AUTH=true
export API_KEY=[Google API Key]
export CLIENT_ID=[Google Client ID]
npm run build
cd dist
npx servor 
```

**Comment by parthparulekar** [comment]
Thanks @BrunnerLivio. I've tried those steps several times but with no luck.

Right, you can't use 'export ENABLE_GOOGLE_AUTH=true' on Windows, so I've been using
set, setx, and even npx cross-env to set these environment variables. However, when I set these, I don't get prompted to authenticate to Google. It simply skips and goes to my radar (I am signed out).

Simply setting the environment variables doesn't seem to be working. They are printed when I console.log() them, but they are not triggering any Google Authorization.

**Comment by parthparulekar** [comment]
And I understand the different between 'npm run build' and 'npm run dev' but I was using 'npm run dev' previously. Regardless, Google Auth works on neither.

**Comment by ar000n** [comment]
Hi @parthparulekar 

Even after setting environment variables, Google Authentication did not work for you? Just make sure you have latest fork.

**Comment by parthparulekar** [comment]
Yeah, I have the latest version of the BYOR repo. Just git cloning it, setting env variables, and running it.
