### ISSUE TITLE
Bug: Impossible to NPM install cause of Node-sass

### ISSUE THREAD

**Issue by gabbloquet** [thoughtworks/build-your-own-radar#158]
Hi team 👋🏻

Impossible to npm install the project cause of 404 on Node sass package downloading for version 4.13.

![image](https://user-images.githubusercontent.com/25029077/94290059-fc66f700-ff59-11ea-9579-d101e2c36d99.png)

Maybe upgrade it to 4.14 🤔

Have a nice day

**Comment by gabbloquet** [comment]
ERROR: Permission to thoughtworks/build-your-own-radar.git denied to gabbloquet. 😢

**Comment by cookstaar** [comment]
Try deleting package-lock.json

**Comment by gabbloquet** [comment]
Node-sass is deprecated, we have to use SASS ;) 
Thanks @cookstaar , i close this issue.
