### ISSUE TITLE
No radar generated

### ISSUE THREAD

**Issue by mattrussell-sonocent** [thoughtworks/build-your-own-radar#159]
I tried to generate a radar using the example public sheet (https://docs.google.com/spreadsheets/d/1Mw7UayaII7cp4uABQ0uzamvMgevrdGDJk0Hj8lrzgyA/edit#gid=0). On submitting, I get the message, "BUILDING YOUR RADAR...Your Technology Radar will be available in just a few seconds". However, even after many minutes, no result is shown. I've tried running it locally using the documented Docker recipe, with similar symptoms. No errors are shown in the Docker container logs.

**Comment by sbergia** [comment]
Same issue on my side...
Tried with different browsers, disabling ad blockers... no difference...

**Comment by renugasaraswathy** [comment]
Thank you @mattrussell-sonocent @sbergia for reporting. We are looking into this.

**Comment by jawahars16** [comment]
It was an issue with publish option in that sheet. Fixed now. @mattrussell-sonocent @sbergia Please verify and let us know if you face any issues.

**Comment by maryamltu** [comment]
> I tried to generate a radar using the example public sheet (https://docs.google.com/spreadsheets/d/1Mw7UayaII7cp4uABQ0uzamvMgevrdGDJk0Hj8lrzgyA/edit#gid=0). On submitting, I get the message, "BUILDING YOUR RADAR...Your Technology Radar will be available in just a few seconds". However, even after many minutes, no result is shown. I've tried running it locally using the documented Docker recipe, with similar symptoms. No errors are shown in the Docker container logs.

is it solved? or not yet?

**Comment by Rajik** [comment]
Closing this issue as it is fixed from our side.
