### ISSUE TITLE
Example of supplying content directly in code

### ISSUE THREAD

**Issue by emmanuel** [thoughtworks/build-your-own-radar#16]
In the README.md, under "More complex usage", there is mention of skipping the Google Sheet:
> or you can also insert all your data straight into the code.

Please provide an example of how to bypass the `GoogleSheetInput` and populate the data in code.

**Comment by psjay** [comment]
+1

**Comment by Rajik** [comment]
@turneand We are so glad to know that this is going to be useful for you! Thank you for looking into the code and giving us suggestions to refactor. You are welcome to give us a pull request, please do so.

**Comment by miguecoll** [comment]
We have bypassed the Googleshhet selection form symply hardcoding the URL as a var on factory.js:

---
const GoogleSheetInput = function () {
    var self = {};

    self.build = function () {
        var hardCodedCrap = 'sheetId=URL_FOR_GOOGLE_SHEET?usp=sharing'
        var domainName = DomainName(hardCodedCrap);
        var queryParams = QueryParams(hardCodedCrap);
---

We  find usefull to have the data on googlesheet but we want to have it "preselected".

**Comment by viveksoundrapandi** [comment]
@emmanuel You can put the csv file in the same folder as the html file that runs  D3 javascript code, and change the code to something like d3.csv("file.csv")
**File**: `/src/util/factory.js`
**Change line 107 in function** :` const CSVDocument = function (url) {`
**From**: `d3.csv(url, createBlips);`
**To**: `d3.csv("local_file.csv", createBlips);`

**Comment by sgarap** [comment]
@viveksoundrapandi Is this approach working for you? It did't for me. I can see teh home page to enter the url. When i enter the csv name, i see the following error. 

> Oops! It seems like there are some problems with loading your data. 
> Please check FAQs for possible solutions.

**Comment by bharathnatarajan1** [comment]
[@viveksoundrapandi](url) I have also tried the approach you suggested. it didn't work for me as well. Any further suggestions?

**Comment by gustavz** [comment]
I am also interested to get it run with local csv files.

> @emmanuel You can put the csv file in the same folder as the html file that runs D3 javascript code, and change the code to something like d3.csv("file.csv")
> **File**: `/src/util/factory.js`
> **Change line 107 in function** :` const CSVDocument = function (url) {`
> **From**: `d3.csv(url, createBlips);`
> **To**: `d3.csv("local_file.csv", createBlips);`

does not work

**Comment by briancurranengie** [comment]
I wanted to host this myself and have it automatically load content from a local CSV file. I got it working by editing the `GoogleSheetInput` function in `src/util/factory.js` to never load the form and automatically call the `CSVDocument` function:
```
const GoogleSheetInput = function () {
  var self = {}
  var sheet

  self.build = function () {
    var domainName = DomainName(window.location.search.substring(1))
    var queryString = window.location.href.match(/sheetId(.*)/)
    var queryParams = queryString ? QueryParams(queryString[0]) : {}

    sheet = CSVDocument("data.csv")
    sheet.init().build()
  }

  return self
}
```
I initially put `data.csv` in a newly created `dist` folder at the root of the repo, but this seems like not an ideal pattern for Node.js (I am not a Javascript developer at all), so I created a new `assets` folder at the root of the repo, created the `assets/data.csv` file, and edited `webpack.config.js` to use this folder as the content base when running locally:
```
  devServer: {
    contentBase: './assets',
    host: '0.0.0.0',
    port: 8080
  }
```
I still haven't figured out a good way to deploy this (will probably try to deploy it to ECS Fargate) and make sure the CSV file is available and loaded properly, but this got it working for local development at least.

**Comment by brianpcurran** [comment]
I wanted to host this myself and have it automatically load content from a local CSV file. I got it working by editing the `GoogleSheetInput` function in `src/util/factory.js` to never load the form and automatically call the `CSVDocument` function:
```
const GoogleSheetInput = function () {
  var self = {}
  var sheet

  self.build = function () {
    var domainName = DomainName(window.location.search.substring(1))
    var queryString = window.location.href.match(/sheetId(.*)/)
    var queryParams = queryString ? QueryParams(queryString[0]) : {}

    sheet = CSVDocument("data.csv")
    sheet.init().build()
  }

  return self
}
```
I initially put `data.csv` in a newly created `dist` folder at the root of the repo, but this seems like not an ideal pattern for Node.js (I am not a Javascript developer at all), so I created a new `assets` folder at the root of the repo, created the `assets/data.csv` file, and edited `webpack.config.js` to use this folder as the content base when running locally:
```
  devServer: {
    contentBase: './assets',
    host: '0.0.0.0',
    port: 8080
  }
```
I still haven't figured out a good way to deploy this (will probably try to deploy it to ECS Fargate) and make sure the CSV file is available and loaded properly, but this got it working for local development at least.

**Comment by setchy** [comment]
@devansh-sharma-tw with byor supporting cav, Jason, Google sheets, this issue may be able to be closed
