### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by mike-thompson-h** [thoughtworks/build-your-own-radar#164]
I have tried building an image based from this Thoughtworks git clone. However, when I run "docker image build ." to rebuild the image using a local image of node as the base of the Dockerfile, I find the following line to be hanging and not proceeding with the rest of the code:

![Capture](https://user-images.githubusercontent.com/76072274/106480151-facab400-64a2-11eb-8b67-65158ee51a7b.PNG)

Please could you help me with this issue.

**Comment by SARAN-thala** [comment]
Could you try with `14.15.4 LTS` version.

**Comment by cookstaar** [comment]
Not sure if its related but I had to delete package-lock.json when installing locally as one of teh pinned dependencies no longer exists, could be related?

**Comment by SARAN-thala** [comment]
I never checked this flow. worth to tryout.

**Comment by mike-thompson-h** [comment]
Thanks everyone, it is working locally on my own machine. It seems to be proxy related to the machine on my company's network, but will be investigating further.
