### ISSUE TITLE
Creating radars from multiple sheets

### ISSUE THREAD

**Issue by maggrey** [thoughtworks/build-your-own-radar#17]
This is not an issue. Just a question. What file should be edited to be able to add multiple Google Sheets to the code? The docs say you can add Google Sheets to the code.

**Comment by arunvelsriram** [comment]
Hi,
Sheet ID is given as input to the service.
What do you mean by add Google sheets to the code ?

**Comment by maggrey** [comment]
In the README file under More complex usage it says

To create the data representation, you can use the Google Sheet factory, or you can also insert all your data straight into the code.

I would like to insert the google sheet ids into the code rather than taking it as input. I don't know if that makes sense.

**Comment by gustavz** [comment]
What I would be interested in, if it is possible to input multiple Google sheet IDs and then after building the radar choose which one to combine / show.

The radar says 
`Choose a sheet to populate radar`
But there is no option to acutally add more sheets to populate, or am I wrong?
