### ISSUE TITLE
Private google sheets not accessible

### ISSUE THREAD

**Issue by cakkinep** [thoughtworks/build-your-own-radar#170]
Has anyone been successful in using a private google sheet to use with techradar.
I am running this locally on my machine in a docker container as per the instructions.

I have set the flags 
export ENABLE_GOOGLE_AUTH=true
export API_KEY=[Google API Key]
export CLIENT_ID=[Google Client ID]

as part of docker container run command.
 But no luck yet in loading the sheet, i have been able to successfully load the sample google sheet into the radar.

Any help is greatly appreciated.

**Comment by maryamltu** [comment]
> Has anyone been successful in using a private google sheet to use with techradar.
> I am running this locally on my machine in a docker container as per the instructions.
> 
> I have set the flags
> export ENABLE_GOOGLE_AUTH=true
> export API_KEY=[Google API Key]
> export CLIENT_ID=[Google Client ID]
> 
> as part of docker container run command.
> But no luck yet in loading the sheet, i have been able to successfully load the sample google sheet into the radar.
> 
> Any help is greatly appreciated.

hej, where did u change for this? just the default value? or change it? which file?

**Comment by eskimoquinn** [comment]
I am having this same issue. I have set these as environment variables in my Dockerfile. However when I run the app, I  am seeing this error:
client_id and scope must both be provided to initialize OAuth.

**Comment by marisahoenig** [comment]
This issue should be fixed now with the newest design. Please reopen if you're still having any issues.
