### ISSUE TITLE
Is this repo still alive? Many PR's but none making it into master.

### ISSUE THREAD

**Issue by GaTechThomas** [thoughtworks/build-your-own-radar#178]
Is this repo still alive? Many PR's but none making it into master.

**Comment by Vaishnavij** [comment]
@GaTechThomas Thanks for your question, We are still actively maintaining this repo.  Apologies for the lull in merging of PR's and closing of issues. We are trying our best to maintain the balance between our internal priorities and staying committed to BYOR.  

Thanks,
BYOR Team
