### ISSUE TITLE
How to configure the radar to run on apache server?

### ISSUE THREAD

**Issue by rosanocangussu** [thoughtworks/build-your-own-radar#188]
I created a virtualhost in apache server with the content

/etc/httpd/conf.d/radar.conf
<VirtualHost *:443>

SSLEngine on
SSLProtocol all -SSLv2
SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5:!SEED:!IDEA

 

SSLCertificateFile <path .cer>
SSLCertificateKeyFile <path .key>

ServerName mysite.org

ProxyRequests On
ProxyPass /radar http://localhost:8080
ProxyPassReverse /radar http://localhost:8080

ErrorLog /var/log/httpd/radar-error.log
CustomLog /var/log/httpd/radar-access.log combined

</VirtualHost>

But whem i access the url https://meusite.org/radar, receive the folow content
    
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link href="/images/favicon.ico" rel="icon"/>
  <link href="/main.81af0353a71cb067f96c.css" rel="stylesheet"></head>

  <body>
  <script type="text/javascript" src="/main.81af0353a71cb067f96c.js"></script></body>
</html>

**Comment by BrunnerLivio** [comment]
Since you use the /radar path it wont resolve the JS files correctly. Either you create a PR adding support for custom path prefix, or change your url to a subdomain. E.g. radar.meusite.org

**Comment by rosanocangussu** [comment]
Thanks @BrunnerLivio !
