### ISSUE TITLE
The example table doesn't work

### ISSUE THREAD

**Issue by Win-Dox** [thoughtworks/build-your-own-radar#193]
I downloaded a table with an example, uploaded it to my disk, tried to build a radar using the link from my Google drive, and when building, I get an error in the browser console
https://docs.google.com/spreadsheets/d/1OMQvrnN3qwzfBx8y6I77EskuTf10iESeh1Wpvw8hz_4/edit#gid=0
Error:
Uncaught TypeError: Cannot read property 'isSignedIn' of null
    at Object.login (main.789f8f3ee623709c5d19.js:91)
    at Object.loadedCallback (main.789f8f3ee623709c5d19.js:27)
    at main.789f8f3ee623709c5d19.js:91
    at e.Er (cb=gapi.loaded_0:236)
    at Yk (cb=gapi.loaded_0:239)
    at Tk (cb=gapi.loaded_0:239)
    at _.Ek.ru (cb=gapi.loaded_0:239)
    at Dk (cb=gapi.loaded_0:231)

Also I can this error with any files

**Comment by Win-Dox** [comment]
This error occurs if the file is not published on the Internet. The key, clientid, and authorization flag are specified...

**Comment by sidyatish** [comment]
@Win-Dox this issue is addressed now. Please try again. If you see a window to switch account Please do **reselect** your google account and **give sheets permission** in the window that pops up. This is due to recent changes made from the google sheets API. Thank you.

**Comment by marisahoenig** [comment]
Closing as this issue should be fixed. Feel free to reopen if you're still experiencing issues.
