### ISSUE TITLE
Print this radar contains empty pages when there is no element in some rings.

### ISSUE THREAD

**Issue by pldupont** [thoughtworks/build-your-own-radar#2]
If a quadrant doesn't have element in one ring (like assess), the print option will generate an empty page.

**Comment by NivedhaSenthil** [comment]
Hi @pldupont thanks for bringing this up, we are aware of this issue and planned to fix it for next release.
Meanwhile if you have a solution feel free to raise a pull request.

**Comment by SARAN-thala** [comment]
Hi @pldupont,

We have fixed this issue in our latest release. Thanks to PR #27.

Thank you too for raising this with us.
