### ISSUE TITLE
Demo link from readme doesn't work

### ISSUE THREAD

**Issue by panahi** [thoughtworks/build-your-own-radar#200]
Both the direct link "this visualization" and linking the google sheet via the UI at https://radar.thoughtworks.com/ result in javascript errors on the "Building your radar page"

https://radar.thoughtworks.com/?sheetId=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1OMQvrnN3qwzfBx8y6I77EskuTf10iESeh1Wpvw8hz_4%2Fedit%3Fusp%3Dsharing

<img width="1075" alt="Screen Shot 2021-08-16 at 10 55 58 AM" src="https://user-images.githubusercontent.com/1176656/129584180-88051bf4-b3c8-4e95-a19f-cfa648e6a1f9.png">

**Comment by panahi** [comment]
Note I can directly access the source spreadsheet https://docs.google.com/spreadsheets/d/1waDG0_W3-yNiAaUfxcZhTKvl7AUCgXwQw8mdPjCz86U/edit#gid=0

**Comment by Vaishnavij** [comment]
@panahi : Thanks for bringing this to our attention. We will look at this and get back to you!

**Comment by sidyatish** [comment]
@panahi , we checked on this and could see that when the sheet is published as a webpage, the google API is causing some issue and we are getting 404 response

```
{
"error": {
"code": 404,
"message": "Requested entity was not found.",
"status": "NOT_FOUND"
}
}
```

**As a workaround, publishing the sheet as a CSV will help.**
Meanwhile we will be looking into the above issue

**Comment by sidyatish** [comment]
The issue has been fixed and the URL now works.

**Comment by sidyatish** [comment]
The issue has been fixed and the URL now works.
