### ISSUE TITLE
Unable to render Radar GUI

### ISSUE THREAD

**Issue by sachudj** [thoughtworks/build-your-own-radar#201]
It fails to do GET on the publically published Google Sheet

Tried the one given in the example. Still same. 

![image](https://user-images.githubusercontent.com/14989223/129879185-3dace322-aea9-4bd6-83e9-f4e4e4bf4fff.png)

**Comment by Vaishnavij** [comment]
Thanks @sachudj for pointing out this issue. Will look at it and keep you posted about the same.

**Comment by Vaishnavij** [comment]
Tracking this in issue #200
