### ISSUE TITLE
Build Your Own Radar is currently unavailable. Sorry for the inconvenience!

### ISSUE THREAD

**Issue by azmathasan92** [thoughtworks/build-your-own-radar#202]
We are using our own radar, but we cannot create our own radar from today and get the following message on the ThoughtWorks website. (https://www.thoughtworks.com/radar/byor)

```
Build Your Own Radar is currently unavailable. Sorry for the inconvenience!
```

I tried with both google sheet as well as CSV files. but did not work for me. 

Is there some issue with ThoughtWorks radar going on? if yes how long will it take to fix?

**Comment by sidyatish** [comment]
The issue has now been fixed and BYOR is up and running now.
