### ISSUE TITLE
Public google spreadsheet don't work anymore

### ISSUE THREAD

**Issue by apracine** [thoughtworks/build-your-own-radar#210]
The radar is asking for an authentication when a google spreadsheet url is provided, even if the spreadsheet is published. The error seems to be related to the changes in this PR : https://github.com/thoughtworks/build-your-own-radar/blame/master/src/util/factory.js#L103

The radar still works if you provide the CSV link from the spreadsheet, but then you lose the pages (tabs) and the title becomes PUB?OUTPUT=CSV.

**Comment by Vaishnavij** [comment]
@apracine : There is a recent change in google API, which requires authentication or API KEY to read information like sheet title etc. To accomodate this change, now BYOR requires authentication by default irrespective of if the sheet is  public or not.
