### ISSUE TITLE
How to Deploy in Server, Specially Azure

### ISSUE THREAD

**Issue by michelpf** [thoughtworks/build-your-own-radar#22]

**Comment by michelpf** [comment]
Sorry, I figure out that webpack generate the html + css + js files ready to deploy for static web hosting. So, there is no arrangements for Azure. Pay attention to the index.html, all references of files contains "/" at he beginning, which indicates to the browser to search not on relative path, but absolute, so the browser was trying to find at C:// (in Windows).

**Comment by gustavz** [comment]
Hey @michelpf, Did you manage to deploy it on Azure somehow?

**Comment by michelpf** [comment]
Hey @gustavz it is a bunch of static files, so you can deploy in Azure Blobs ou WebApps. I prefer Blobs because now they are more friendly with HTML hosting, just like S3.

**Comment by gustavz** [comment]
Can you name the steps or is there any tutorial on how to deploy a project like this on Blovs or WebApps?

**Comment by michelpf** [comment]
Just copy the files in Azure Blobs (just like a Dropbox file manager in Azure console) then put the container public. 
Try to understand how to host static files in Azure Blobs. It is a good start. 😄

**Comment by gustavz** [comment]
@michelpf  Azure Blobs currently does not work for me.
How can i deploy it on Azure Web Apps?
