### ISSUE TITLE
Oops! We can't find the Google Sheet you've entered

### ISSUE THREAD

**Issue by stulika19** [thoughtworks/build-your-own-radar#229]
Hi, 
I am trying to create the tech radar by following the steps mentioned here https://www.thoughtworks.com/radar/how-to-byor.
I tried with the sample file provided in the link https://docs.google.com/spreadsheets/d/1riuKb6gdPOmUbWi_DeoseV5oMiCGhE9vIqGzuKVHGfA/edit#gid=0 and with my own file using both private and publish to web options.  For every option, I keep getting  "Oops! We can't find the Google Sheet you've entered".
Can you please let me know if there is any additional step that needs to be taken care of?

**Comment by sidyatish** [comment]
Hi @stulika19, are you trying to create radar using https://radar.thoughtworks.com/ ? If yes could you confirm if you had successfully signed in using google?

**Comment by stulika19** [comment]
Hi @sidyatish,
Yes I am using https://radar.thoughtworks.com/ . I am signed into google account. I tried logging in again using icognito mode also but same error.

**Comment by sidyatish** [comment]
@stulika19 Please note that radar will not work in incognito mode. In normal window, please try signing out of google and signing in again while trying to build radar. While signing again, google prompt asks permission to access the sheets. Kindly provide that and try again.

**Comment by stulika19** [comment]
@sidyatish Hi I tried removing tech radar from my apps list in google settings and then tried again to give permission to access google sheets. Still  I am getting the same error.

**Comment by sidyatish** [comment]
Could you confirm if you are using this link : https://docs.google.com/spreadsheets/d/1riuKb6gdPOmUbWi_DeoseV5oMiCGhE9vIqGzuKVHGfA/edit#gid=0 directly?
Since we are able to generate radar using this link directly.

**Comment by stulika19** [comment]
Right now I am trying with a sample excel https://docs.google.com/spreadsheets/d/1Ne7RsoF1YAD8Ed7bVbSF13Kkh7zoviOe/edit#gid=1244912168
which is a copy of the excel https://docs.google.com/spreadsheets/d/1riuKb6gdPOmUbWi_DeoseV5oMiCGhE9vIqGzuKVHGfA/edit#gid=0
I have hosted the copy in my google drive.

**Comment by stulika19** [comment]
Strange enough the sample link is also giving the same error 
![image](https://user-images.githubusercontent.com/6558167/145387121-4d54c777-29cc-42af-897c-923f79ad1eba.png)
![image](https://user-images.githubusercontent.com/6558167/145387165-6b646df9-7c76-4cdf-a25a-ee1d7f4f67ad.png)

**Comment by sidyatish** [comment]
Thats strange 😐. To help us identify the issue we need what error the console is throwing. Could you help us get that?
right click->inspect element from there there is a console tab. A screenshot of the messages there could help us narrow down the problem.

**Comment by stulika19** [comment]
This time it generated the radar with the sample excel url . But I got this error in the console.
![image](https://user-images.githubusercontent.com/6558167/145388878-78b52d42-73b0-49e2-8b59-9f4c4c94f99b.png)

When I tried with the copy of it hosted in my google drive, I got this error in console and radar was not generated
![image](https://user-images.githubusercontent.com/6558167/145389265-2560aeb6-67df-45b1-a21d-2ca78cef70a3.png)

**Comment by sidyatish** [comment]
@stulika19 As you mentioned that the sample link is now working, the second link that you are using seems to be inaccessible. Are you keeping the sheet private? If not, please make sure that the sheet is published.

**Comment by stulika19** [comment]
There are two options mentioned in the how to build your radar page. One of them is to use the sheet url if you dont want to publish i.
Private Google sheet: If you prefer to keep your radar private, simply enter the Google sheet URL.
Is this not supported?

**Comment by sidyatish** [comment]
@stulika19 Private sheets are supported. We just verified by copying the sample sheet to our own drive via google sheets and we are able to create radar without issues. 

One thing that we observed from the url you shared is the id of the sheet : `https://docs.google.com/spreadsheets/d/1Ne7RsoF1YAD8Ed7bVbSF13Kkh7zoviOe/`  The sheet id value followed by /d/ seems to be just 33 characters whereas any sheet that we create (including the sample one) seems to have 44 characters. 

Could you try copying the sample sheet again (File->make a copy) into your drive and use that URL? Let us know if the id is still around this size?

**Comment by sidyatish** [comment]
@stulika19 we just found out that:
1. Uploading an excel file (**.xlsx**) to google drive
and
2. Copying a sheet from Google sheets (File->Make a copy) are not the same. 

Apparently Google sheets API will be able to get sheet information and content only with the case of (2).
We will try to work on this scenario.

Meanwhile, could you please follow the option (2) to copy the sheet directly to your drive without downloading it as an excel file? I am sure it will work in this case.

Thank you so much for bringing this to our notice.

**Comment by stulika19** [comment]
I tried making a copy and using that but same error on webpage and in the console. 
The length of the id is also of same length.
The first one is uploaded one and the second one is after making a copy - 
https://docs.google.com/spreadsheets/d/1Ne7RsoF1YAD8Ed7bVbSF13Kkh7zoviOe/edit#gid=1244912168
https://docs.google.com/spreadsheets/d/1r_379b2x7lan_KzTU2ZUhDAJdei2AriO/edit#gid=826400120

**Comment by stulika19** [comment]
Hi, is there any other option I can try to make it work ?

**Comment by stulika19** [comment]
I found the problem. The tech radar works only with Google sheets.

When an excel file is uploaded to google drive, the spreadsheet id generated for it is of a different length than when it is created directly in google drive as a new sheet. So if I upload an excel file to google drive, the tech radar gives the error of can't find google sheet.

If I have to make that file work, I will need to save the file as google sheets -
![image](https://user-images.githubusercontent.com/6558167/146103729-03117533-fd25-4b7e-a8e3-bce292f60378.png)
This changes the spreadsheet id length as well.

Any other option like making a copy of it or sharing the file will not work.

Making a copy option will only work when the file was already created using google sheet.

I am not sure that while generating the tech radar whether you are checking the spreadsheet id length or by any other mechanism distinguishing the type of file, but I think it will be good to put this information on the instructions page that excel files uploaded to google drive will not work till the time you fix this issue.

**Comment by marisahoenig** [comment]
This issue should be resolved with recent changes. Please reopen if you're still experiencing issues.
