### ISSUE TITLE
No radar displayed, using dockerfile, CLIENT_ID and API_KEY

### ISSUE THREAD

**Issue by cobbr2** [thoughtworks/build-your-own-radar#230]
I'm running 
```
docker run --rm -p 8080:80 -e CLIENT_ID="${GOOGLE_CLIENT_ID}" -e API_KEY="${GOOGLE_API_KEY}" wwwthoughtworks/build-your-own-radar
```
with image `b9a8c0ead7c2` . On localhost:8080 I get the prompt for a spreadsheet, but when I enter my Google spreadsheet URL I get only the "Building your Radar" screen. Nothing interesting is logged on my docker output.

I've verified that I'm using the same CLIENT_ID I used to generate the spreadsheets in the first place, and just created the API key this evening.

(Oh, and thanks @bjornswift for #215 so I didn't go crazy :) ).

**Comment by marisahoenig** [comment]
Closing as stale. Mentioned fix was merged last year.
