### ISSUE TITLE
App does not have permission to sheet

### ISSUE THREAD

**Issue by Cristian-Vt** [thoughtworks/build-your-own-radar#235]
When I enter the url to the sheet I want the app to process I get this message
"Oops! Looks like you are accessing this sheet using"

Steps I did to run the app locally.

1. Create OAuth 2.0 Client IDs Credentials and set URI to local host in https://console.cloud.google.com/
2. Create new project in https://console.cloud.google.com/ and give access to test user
3. run docker container and able to authenticate with google user.
4. enter the google sheet with correct headers and permissions given to the sheet to same user that I used at step 3

After step 4 I get:

Oops! Looks like you are accessing this sheet using <user>@gmail.com, which does not have permission.Try switching to another account.

Note: When I use public link for the sheet from my account and enter it in the https://radar.thoughtworks.com, I can see the dashboard for my sheet.

Can anyone help me understand how I can provide permissions to my app to allow my user have permissions, please?

**Comment by sidyatish** [comment]
@Cristian-Vt. Thanks for the details. While getting this message. Could you try  clicking "Switch Account" button and perform a google sign in again. This time, please ensure you have checked the checkbox that asks permission to access sheets. Please let us know if that works

**Comment by Cristian-Vt** [comment]
@sidyatish I've applied the suggestion, I still get the same message.

**Comment by Cristian-Vt** [comment]
problem solved thanks to @sidyatish. The new Google updates require you to give access to enable the Google Sheet API. Find attachments bellow.
<img width="791" alt="Screenshot 2022-01-11 at 09 46 56" src="https://user-images.githubusercontent.com/95423007/148919698-446b78c4-a89f-4d11-bd7d-64bb964d5a55.png">
<img width="673" alt="Screenshot 2022-01-11 at 09 47 28" src="https://user-images.githubusercontent.com/95423007/148919706-bf1f5ebc-8884-4089-ad8e-13d230f4b452.png">
