### ISSUE TITLE
blip positioning within ring

### ISSUE THREAD

**Issue by DarrenRatcliffe** [thoughtworks/build-your-own-radar#24]
Hi, this is a question as opposed to an issue.

How are blips positioned within the ring? It isn't immediately obvious to me how you can position a blip to be closer to the Adopt ring as opposed to the Assess ring if the blip is placed in the trial ring?

**Comment by jean** [comment]
I came here to log the same issue. At the [FAQ, What significance is there to the position of a blip inside its quadrant and ring?](https://www.thoughtworks.com/radar/faq) we read: "_In contrast we do pay attention to the radial position._"
Does this version of the radar support that?
