### ISSUE TITLE
Enable automated dependency updates for this repo

### ISSUE THREAD

**Issue by setchy** [thoughtworks/build-your-own-radar#249]
Enable an automated dependency update tool for this repository, such as dependabot or renovate.  

As far as I'm aware, everything can be updated except d3-tip (keep with 0.7.1) without refactoring the way tooltips are used

**Comment by setchy** [comment]
@devansh-sharma-tw - nudging this to see if you'd be interested in enabling the [Renovate GitHub app](https://github.com/apps/renovate) for this repository to help with automatically raising PRs for any outdated dependencies

**Comment by devansh-sharma-tw** [comment]
Hi @setchy , thanks for the suggestion! We do plan to do a dependency review/cleanup once we are done moving away from the old UI code completely. Post that we can explore the options (Dependabot and Renovate) you have suggested here.

Thanks!

**Comment by setchy** [comment]
Closing this ticket, as I've observed [dependabot performing some package updates](https://github.com/thoughtworks/build-your-own-radar/pulls?q=is%3Apr+author%3Aapp%2Fdependabot+is%3Aclosed)
