### ISSUE TITLE
width of rings not auto adjusting based on text size

### ISSUE THREAD

**Issue by andy9876** [thoughtworks/build-your-own-radar#25]
Hello - Is there a setting I can tweak so that the width of the ring is at least the width of its text label?  Currently the text is getting overlapped with the next ring since there are not many blips in that ring.  The issue does not happen when using a larger screen size/monitor

**Comment by Rajik** [comment]
Hello Andy,
This is a known bug and there is no fix for that yet.
You are welcome to fix and it give us a pull request. That would be much appreciated.
Thanks!

**Comment by andy9876** [comment]
yes I have a fix for this.  I'm working on approval to contribute a pull request

**Comment by marisahoenig** [comment]
Hi @andy9876 — this issue should be fixed with the new design refresh. We now have blip limits for each ring based on the number of max blips that can fit there. If you're still having this issue, feel free to reopen this.
