### ISSUE TITLE
Not able to view the Radar

### ISSUE THREAD

**Issue by fahadanwarONS** [thoughtworks/build-your-own-radar#253]
I have copied the file into my git repo (which is public) but not able to access the radar and getting following error

Access to fetch at 'https://github.com/ONSdigital/Radar/blob/main/ThoughtWorks%20Technology%20Radar%20Vol.%2026%20-%20Build%20your%20Technology%20Radar.csv' from origin 'https://radar.thoughtworks.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I am using https://radar.thoughtworks.com/ page and adding my csv file link in the page.

Any idea what needs to be done?

**Comment by jemerald** [comment]
You need the URL for the raw file

![image](https://user-images.githubusercontent.com/9168432/163708710-6f9d0d4f-caa6-4415-9e8d-c5783d100f1d.png)

```
https://raw.githubusercontent.com/ONSdigital/Radar/main/ThoughtWorks%20Technology%20Radar%20Vol.%2026%20-%20Build%20your%20Technology%20Radar.csv
```

**Comment by fahadanwarONS** [comment]
Thanks this is resolve now :).
