### ISSUE TITLE
download link of specific version

### ISSUE THREAD

**Issue by bhaskarsantoshk** [thoughtworks/build-your-own-radar#258]
I'd like to download the specific version , could you share the link? The regular/conventional url is not working

https://github.com/thoughtworks/build-your-own-radar/archive/refs/tags/v0.3.0.zip

**Comment by marisahoenig** [comment]
Hi @bhaskarsantoshk, is this what you're looking for? https://github.com/thoughtworks/build-your-own-radar/releases/tag/v1.0.0
