### ISSUE TITLE
Unable to load data file from github-public repo

### ISSUE THREAD

**Issue by rczone9999** [thoughtworks/build-your-own-radar#274]
Team,

looking for some solution on how to upload a github file into the Thoughtworks BYOR

Unable to load data file from github-public repo ..Please find the log from docker..the log shows the file has been uploaded but my webpage url does nothing after uploading the file

 [`10.0.10.100 - - [16/Sep/2022:21:26:48 +0000] "GET / HTTP/1.1" 200 2617 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:26:48 +0000] "GET /main.15c7e60eb148d4f1bb7e.css HTTP/1.1" 200 13482 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:26:48 +0000] "GET /images/tw-logo.png HTTP/1.1" 200 13041 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/" "Mozilla/5.0 (WindowsNT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:26:49 +0000] "GET /main.471b7d51734cbe88e2ca.js HTTP/1.1" 200 1073786 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:26:50 +0000] "GET /images/tech-radar-landing-page-wide.png HTTP/1.1" 200 16509 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/main.15c7e60eb148d4f1bb7e.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:26:50 +0000] "GET /images/favicon.ico HTTP/1.1" 200 1150 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:38:56 +0000] "GET /?sheetId=https%3A%2F%2Fgithub.com%2Frczone9999%2Ftest%2Fblob%2Ffcb3e8a6a405603b7db93865b27de6455925001d%2Fradar.csv HTTP/1.1" 200 2617 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:38:57 +0000] "GET /main.15c7e60eb148d4f1bb7e.css HTTP/1.1" 304 0 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/?sheetId=https%3A%2F%2Fgithub.com%2Frczone9999%2Ftest%2Fblob%2Ffcb3e8a6a405603b7db93865b27de6455925001d%2Fradar.csv" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:38:57 +0000] "GET /main.471b7d51734cbe88e2ca.js HTTP/1.1" 304 0 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/?sheetId=https%3A%2F%2Fgithub.com%2Frczone9999%2Ftest%2Fblob%2Ffcb3e8a6a405603b7db93865b27de6455925001d%2Fradar.csv" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:38:57 +0000] "GET /images/tw-logo.png HTTP/1.1" 304 0 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/?sheetId=https%3A%2F%2Fgithub.com%2Frczone9999%2Ftest%2Fblob%2Ffcb3e8a6a405603b7db93865b27de6455925001d%2Fradar.csv" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"
10.0.10.100 - - [16/Sep/2022:21:38:57 +0000] "GET /images/tech-radar-landing-page-wide.png HTTP/1.1" 304 0 "http://vpce-01ac241a5dfccda73-9s5kxnh9.vpce-svc-0ecf3bb911e65635e.us-west-2.vpce.amazonaws.com/main.15c7e60eb148d4f1bb7e.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" "-"`

**Comment by rczone9999** [comment]
[radar.csv](https://github.com/thoughtworks/build-your-own-radar/files/9588463/radar.csv)
Attached the file

And the page got stuck here....

BUILDING YOUR RADAR...
"Your Technology Radar will be available in just a few seconds"

**Comment by sidyatish** [comment]
@rczone9999, thank you for reaching out to us. 
Could you help us elaborate where this file is hosted and how did you obtain this URL?

To use a file hosted in github on BYOR, we need to obtain the 'raw' URL of the file. Clicking on the raw button while viewing the file will help us get the raw URL.

e.g., [here](https://raw.githubusercontent.com/thoughtworks/build-your-own-radar/3266d7fab7b15f055b11b5bff07eeee5030bddea/spec/end_to_end_tests/resources/sheet.csv) is the raw link for CSV in our tests

**Comment by rczone9999** [comment]
> @rczone9999, thank you for reaching out to us. Could you help us elaborate where this file is hosted and how did you obtain this URL?
> 
> To use a file hosted in github on BYOR, we need to obtain the 'raw' URL of the file. Clicking on the raw button while viewing the file will help us get the raw URL.
> 
> e.g., [here](https://raw.githubusercontent.com/thoughtworks/build-your-own-radar/3266d7fab7b15f055b11b5bff07eeee5030bddea/spec/end_to_end_tests/resources/sheet.csv) is the raw link for CSV in our tests

@sidyatish, 

I am able to load the sample file from public git repo with raw URL. For the next steps is it possible to use csv from our internal sharepoint.com URL ? Is it allowed ? I only see the inputs as google sheets, json and csv. Since we are not allowed to use public data feeds, I  want to keep it internal with our BYOR deployment. Please let me know.

Thank you.

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now
