### ISSUE TITLE
are pull requests being accepted for this project?

### ISSUE THREAD

**Issue by andy9876** [thoughtworks/build-your-own-radar#30]
I've noticed issues are not being responded to in a timely manner for this project.  Is it still actively supported?  I have several pull requests I would like to discuss if you are available.  thanks

**Comment by Rajik** [comment]
Hello Andy,
We are grateful to know that you are interested to contribute to this project. We are reviewing pull requests and merging them as and when we could. There might be some delay as we need to check the alignment of the PRs with our product vision. Please share your email address so that we can start our conversations. We are very happy to talk to you and we are looking forward to it. Thanks!

**Comment by andy9876** [comment]
Thanks!  I have some modified code that leverages a local file with a nodejs static file server to retrieve the data from the file instead of using google sheets.  Is this something you guys are already working on?

**Comment by tgriffo** [comment]
@andy9876 I was about to start making a modification to do something pretty similar to what you described. I'm going to wait for your PR to come through then! :)

Any chance you can point me to your code by any chance?

**Comment by andy9876** [comment]
I have two versions - one that reads a tab delimited format and another that uses JSON.  Did you have a preference?

**Comment by tgriffo** [comment]
JSON pls

**Comment by andy9876** [comment]
sorry, i went back and checked and I don't have a JSON version.  one version uses a comma delimited file, another uses a tab delimited file (since there are commas in the data) that uses a | character for end of line.  That second version is the one that uses the static file server.  Which of those two do you prefer?

**Comment by andy9876** [comment]
i am thinking the comma delimited file version will be the easiest to use.  I will submit the pull request once I get approval to do so.

**Comment by tgriffo** [comment]
CSV sounds good Andy! Do you JSON would be a good idea as well?

**Comment by andy9876** [comment]
i think CSV will work, keeps things simple

**Comment by andy9876** [comment]
Hey Tiago - Is there a deadline of when you need to get our code?  How much time do we have to submit it to you?  I am going through an internal approval process so we can submit it, but want to make sure we don't delay you.

**Comment by tgriffo** [comment]
Hi Andy, nothing to worry about too much. Go through your internal process, I'm happy to wait for when the PR get's merged into the code base :)

**Comment by andy9876** [comment]
got approval, working on the pull request now

**Comment by SARAN-thala** [comment]
Hi Andy,
We have looked into you PR and passed on our thoughts about it on that thread. 
Hence we are closing this now.
Thanks!
