### ISSUE TITLE
Print this Radar formatting

### ISSUE THREAD

**Issue by stuartjsmith-aveva** [thoughtworks/build-your-own-radar#301]
There seems to be an issue with the PDF rendering of the radar when I select Print This Radar sheet linked

https://docs.google.com/spreadsheets/d/1Jmi9rp2OcaZqQ7UyH0O-QjSgezN9wAyUJsLPLQmd5Fc/edit?usp=sharing

Steps to repro: Create a radar using the above data source
Click on Print This Radar
PDF output is corrupted

**Comment by stuartjsmith-aveva** [comment]
[
![bug](https://user-images.githubusercontent.com/96117598/223780522-85cbd189-1851-4970-ba95-1dd43b99caa6.png)
](url)

**Comment by marisahoenig** [comment]
Hi @stuartjsmith-aveva. With the design refresh now live, can you let us know if you're still experiencing this issue? Thanks!

**Comment by stuartjsmith-aveva** [comment]
Love the redesign, this seems to have fixed the issue! Thanks!
