### ISSUE TITLE
Issue while deploying Docker Image

### ISSUE THREAD

**Issue by jophisbird** [thoughtworks/build-your-own-radar#308]
When I deploy the via the standard docker run command listed, installation hangs during the NGINX installation portion. I've tried on different AWS instances, and on my local machine as well. Deployment always hangs after "start worker process".

![image](https://user-images.githubusercontent.com/72105201/231897680-83d5dacc-28d0-4343-ac89-8962383e69b2.png)

**Comment by jophisbird** [comment]
It was working, just didn't close complete.

**Comment by devansh-sharma-tw** [comment]
Hi @jophisbird , what logs you see (after the `Starting nginx server...` line) are the standard set of logs nginx gives once it is started in the container. It does not really log anything specific once it is completely up and running.

As starting the nginx server is the last step of the Docker deployment process, if you see any similar logs from nginx (barring error or warning logs), it can be assumed the server is completely up and running.

Thanks!

**Comment by jophisbird** [comment]
> Hi @jophisbird , what logs you see (after the `Starting nginx server...` line) are the standard set of logs nginx gives once it is started in the container. It does not really log anything specific once it is completely up and running.
> 
> As starting the nginx server is the last step of the Docker deployment process, if you see any similar logs from nginx (barring error or warning logs), it can be assumed the server is completely up and running.
> 
> Thanks!

@devansh-sharma-tw Sorry about that, thought I'd closed the issue.

That said, I'd suggest adding" --detach" to avoid confusion, as most docker run commands exit to shell with the container running. I'd also suggest adding "--restart always". With those added to the standard command listed in docs it will be more user friendly to the average inexperienced Docker user. 

Thank you for your response!
