### ISSUE TITLE
Custom quadrant name yields empty quadrant

### ISSUE THREAD

**Issue by jacobmclocklin** [thoughtworks/build-your-own-radar#313]
Hello -
We previously had success with custom quadrant names for all quadrants -- our BYOR radar rendered correctly. Now, our radar quadrants are empty (no blips) unless the quadrant names are exactly the defaults. 

We use BYOR hosted on radar.thoughtworks.com. We supply a Google Sheet that requires authentication. 

When I loaded the radar today, it was empty. I debugged based on the info here: https://www.thoughtworks.com/en-us/radar/byor. That says "you can rename these [quadrants] to anything you want, as long as there are four in total." We were following this correctly (exactly four). In the spirit of trial and error, I renamed the quadrants back to the exact default names, and the radar fully populates.

**Comment by danielkoch** [comment]
@niallr07 stated the right sentence (here is the link: https://github.com/thoughtworks/build-your-own-radar#docker-image). You need to provide environment variables with your custom ring/quadrant information.

For myself: I had to escape everything when using the command line, example:
`-e RINGS="[\"Adopt\", \"Trial\", \"Assess\", \"Hold\"]" -e QUADRANTS="[\"Languages & Frameworks\", \"Methods & Patterns\", \"Platforms & Operations\", \"Software & Tools\"]"`

**Comment by devansh-sharma-tw** [comment]
Hi @jacobmclocklin, apologies for the late reply!
As others have mentioned in this thread, the online hosted version of BYOR (https://radar.thoughtworks.com) now requires the input data to conform to the four rings and quadrants names specified. If you would like to use custom ring and/or quadrant names, you can setup a local instance and set the custom names to it. For a docker setup, you can use the command mentioned by @danielkoch to pass the names. If you would like to run it as a node server itself, you can [export the variables](https://github.com/thoughtworks/build-your-own-radar#more-complex-usage).
Additionally, we have updated the FAQs mentioned, regarding this, here: https://www.thoughtworks.com/en-us/radar/byor. Sorry for the confusion there.

Thanks!

**Comment by jacobmclocklin** [comment]
Ah, well it is unfortunate to lose this feature, and unfortunate that the docs/FAQ were out of sync with the capabilities. But I am thankful for the answer, explanation, and the updates.
