### ISSUE TITLE
Broken Backward Compatibility

### ISSUE THREAD

**Issue by kanekotic** [thoughtworks/build-your-own-radar#315]
Some companies like ours had our links to the radar broken due to the change of the query param from `sheetId` to `documentId`. Would it be possible to maintain this backward compatibility? I know other companies that probably have not noticed yet the breaking change as there are linked in static documentation.
The request will be to implement this with an `expand and contract` strategy not `feature flag`, as it's a change to the contract of the application and requires time for users to migrate and backward compatibility needs to exist temporary.
Also, these changes are not documented anywhere in the [FAQ](https://www.thoughtworks.com/radar/byor#guide) or similar, so it is not that a user of the radar will know upfront what is happening and how to fix. If you implement `expand and contract` you can put a migration path, deprecation notice, and period to migrate to the new contract.

**Comment by kanekotic** [comment]
Sure, thanks.

Navertheless, I think this should be treated as a bug, as it has broken most of the links from ypur users.
my request is if you can keep backward compatible for some time. and provide a migration path explained also in the FAQ of the web.

**Comment by setchy** [comment]
This should do the trick - https://github.com/thoughtworks/build-your-own-radar/pull/318

**Comment by dhair-dml01** [comment]
Please also restore the ability to override quadrant and ring names from Google Sheets.  I have custom quadrant and ring names that no longer work.  Thanks.

**Comment by devansh-sharma-tw** [comment]
Hi @dc2tom @dhair-dml01 , the decision to allow only specific ring and quadrant names on our hosted BYOR website ([radar.thoughtworks.com](https://radar.thoughtworks.com/)) was a conscious one, as part of our v1.0.0 release. We would request you to use a locally hosted setup (using our docker image, for example), which allows for custom names.
We have, however, taken note of this feedback and we'll be discussing this internally. We'll provide the updates here, in case anything changes.

Thanks!

**Comment by dc2tom** [comment]
Thanks for taking the time to reply @devansh-sharma-tw we are using the locally hosted docker setup using the thoughtworks image as a base (adding our own csv radar). We can’t get the RINGS env var to have any effect, previously it was possible to override just based on the content found in the csv without even setting any variables. We’ve had to refactor to match the official ring names now. Happy to raise as a separate issue if you prefer.  I’ve tried a variety of patterns for how to set the variable.

cheers,
Tom

**Comment by marisahoenig** [comment]
Hi folks! The original issue was resolved with the merge of #318 (thanks @setchy!).

@dc2tom please open a separate issue for the rings/quadrant names. As @devansh-sharma-tw mentioned, this was a decision we made due to other issues people were having with the sheet with the order of the rings. We are currently reprioritizing issues and our backlog, so we can take it into consideration. I am closing this issue since it is separate.
