### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by andy9876** [thoughtworks/build-your-own-radar#33]
getting the below error when running npm run dev:
```
ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in C:\Users\TheLetter3\Documents\GitHub\thoughtworks\build-your-own-radar\node_modules\xmlhttprequest\lib
 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36 
```

**Comment by andy9876** [comment]
this can be resolved by added the below line to webpack.config.js, within the module.exports block after the output block.  I've included this fix in my pull request for the local csv file option:
```
externals:[{
    xmlhttprequest: '{XMLHttpRequest:XMLHttpRequest}'
}],
```

**Comment by SARAN-thala** [comment]
Hi Andy,
Thank you for raising this with us.
We have fixed the issue in a slightly different way in our latest release.

Thanks.
