### ISSUE TITLE
Load CSV during container start without clicking submit

### ISSUE THREAD

**Issue by lvthillo** [thoughtworks/build-your-own-radar#339]
We are hosting our own radar in AWS ECS. For an initial start, we have to put the URL to our CSV in the textbox and click submit. 
We tweaked some JS in our fork to automate this by automatically clicking the button during container start. Now it's broken with the latest commits of this fork. Before I start fixing that, I wanted to know if there is a better/cleaner way provided to load a radar automatically without the need to define the .csv and click submit.

**Comment by setchy** [comment]
What about if there was an optional env variable, which if set would auto-load the dataset

**Comment by lvthillo** [comment]
That would be great!

**Comment by devansh-sharma-tw** [comment]
@lvthillo , you can also directly include the encoded CSV URL as a query param itself, for example: https://radar.thoughtworks.com/?documentId=https%3A%2F%2Fraw.githubusercontent.com%2Fthoughtworks%2Fbuild-your-own-radar%2Fmaster%2Fspec%2Fend_to_end_tests%2Fresources%2Fsheet.csv
This way, you can open the CSV rendered radar without pressing the Submit button.

**Comment by lvthillo** [comment]
@devansh-sharma-tw Thanks! Seems also like a good option. Can you point me to the correct place in the code?

**Comment by devansh-sharma-tw** [comment]
Closing this issue. Feel free to reopen in case you have any further questions on this.
