### ISSUE TITLE
Error " npm run dev"

### ISSUE THREAD

**Issue by arjunm183** [thoughtworks/build-your-own-radar#35]
Hello Team,

When we try to run "npm run dev" We get the following error both running from npm install and as well running as a docker container.

Error as follows
ERROR in ./~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in /root/aim_radar/build-your-own-radar/node_modules/xmlhttprequest/lib
 @ ./~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 1.03 kB {0} [built]
        [1] ./~/lodash/lodash.js 540 kB {0} [built]
        [2] (webpack)/buildin/module.js 251 bytes {0} [built]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 30.4 kB [rendered]
        [0] ./~/css-loader?sourceMap!./~/sass-loader!./src/stylesheets/base.scss 28.9 kB {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
webpack: Failed to compile.

Can someone help in fixing this issue for me.

Nodejs version v7.3.0

Thanks and REgards,
ARjun.M

**Comment by andy9876** [comment]
Please see my comment on how to fix this
https://github.com/thoughtworks/build-your-own-radar/issues/33

**Comment by SARAN-thala** [comment]
Hi Arjun,
Thanks for raising this with us. We have fixed this issue in our latest release.
Thanks.
