### ISSUE TITLE
Hard-code ring order?

### ISSUE THREAD

**Issue by chids** [thoughtworks/build-your-own-radar#37]
It seems that the order of the rings in the produced radar depends on the data in the sheet. If the first row is _hold_ then the innermost ring will be hold, the second row is _adopt_ the second innermost ring will that etc.

As the order of the ThoughtWorks radar is, from centre outwards: adopt, trial, assess, hold I think it would make sense for this tool to enforce that order as well.

**Comment by gustavz** [comment]
With the current setting you are able to choose any naming for rings and quadrants, which is more a feature than a bug.

**Comment by m1ke-RSG** [comment]
i have submitted a pull request that adds the option to specifically set a ring order and its even able to display empty rings as well as adding additional options to for the radar creation.
#99

or if it doesnt get confirmed you can use our fork instead: https://github.com/raiffeisensoftware/build-your-own-radar

**Comment by marisahoenig** [comment]
Hi folks! With the recent design refresh, the order of the rings is no longer dependent on your spreadsheet input. Instead, it will show up in the same Adopt, Trial, Assess, Hold (from inside to out) as the [Thoughtworks Technology Radar](https://www.thoughtworks.com/radar).
