### ISSUE TITLE
Class "quadrant-name-group" text/tspan not wrapping in current release

### ISSUE THREAD

**Issue by npfisterIT** [thoughtworks/build-your-own-radar#375]
Minor issue, but have been trying to figure it out for a while now. Running on v1.1.4

Current build shows this:
![image](https://github.com/thoughtworks/build-your-own-radar/assets/105443162/b7497f8c-661e-4fea-9687-6ba4ffb11cf1)

While the https://radar.thoughtworks.com/ page shows this:
![image](https://github.com/thoughtworks/build-your-own-radar/assets/105443162/0e521968-3d1c-44f5-8a7c-b7c8738051a0)

For some reason in the code, the quadrant name text is duplicated like so:
![image](https://github.com/thoughtworks/build-your-own-radar/assets/105443162/6b97483b-8d4c-4989-bf5f-c11f8afc6702)

The text inside of "tspan" does not load while the text in quotes is what is actually loaded. This does not occur on the public site: 
![image](https://github.com/thoughtworks/build-your-own-radar/assets/105443162/a51322c7-9549-4798-a0be-301a0369a7ac)

`wrapQuadrantNameInMultiLine` function in `quadrant.js` may not be behaving correctly, but appears to have been fixed at some point. Would be great to get this working or at least some info on how to fix it myself and have the multiline function work as intended.

**Comment by yashanandan** [comment]
Hi @npfisterIT , 

We have fixed this issue and pushed a new patch version v1.1.5. Kindly take a docker pull and let us know if it is working fine.

**Comment by npfisterIT** [comment]
@yashanandan Wonderful, it looks good. Thank you for the speedy response and fix.
