### ISSUE TITLE
Missing search option

### ISSUE THREAD

**Issue by pldupont** [thoughtworks/build-your-own-radar#4]
It would be nice to have a search option in the radar.

**Comment by NivedhaSenthil** [comment]
Hi @pldupont thanks for bringing this up, we are currently working on this will update soon once done.

**Comment by scpawl** [comment]
@NivedhaSenthil any progress on this feature? I too would find it very useful

**Comment by CBeeson** [comment]
@NivedhaSenthil - did you get anywhere with the search function? This would be great

**Comment by aschonfeld** [comment]
I am beginning work on this feature

**Comment by aschonfeld** [comment]
> I am beginning work on this feature

I have opened a PR to add this feature if someone with access could review it for merging?

**Comment by aschonfeld** [comment]
> > I am beginning work on this feature
> 
> I have opened a PR to add this feature if someone with access could review it for merging?
> #67

Does anyone actually maintain this project anymore?  Has thoughtworks gone belly-up?

**Comment by gustavz** [comment]
what happened to the feature?

**Comment by mohamednajiullah** [comment]
It has been added.
