### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by arunvelsriram** [thoughtworks/build-your-own-radar#41]
Hello. This project has no dependency on jQuery however one (or some) of the GTM tags seem to be using jQuery. So `gtm.js` expects jQuery to be available. Since jQuery is not available an error is being thrown at runtime.

<img width="1668" alt="screen shot 2017-10-25 at 9 50 45 pm" src="https://user-images.githubusercontent.com/6568319/32010684-29de59d0-b9d0-11e7-8e1d-5c1eb6ca7de3.png">

This can be prevented in two ways:
- change the GTM tags to use plain JavaScript
- add jQuery as a dependency in the project (not recommended because this project has no dependency on jQuery so doesn't make much sense)

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now
