### ISSUE TITLE
Origin is not allowed by Access-Control-Allow-Origin.

### ISSUE THREAD

**Issue by mschmid** [thoughtworks/build-your-own-radar#42]
Hi, I have massive problems with the instance running at https://radar.thoughtworks.com.
Does anybody have the same problems? No matter if I use a google sheet or provide a CSV file on my own web server, every time this error appears in the java script console:
[Error] Origin https://radar.thoughtworks.com is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://radar.thoughtworks.com is not allowed by Access-Control-Allow-Origin. (radar.csv, line 0)
[Error] Fetch API cannot load [...]/radar.csv. Origin https://radar.thoughtworks.com is not allowed by Access-Control-Allow-Origin.

**Comment by SARAN-thala** [comment]
Hi @mschmid,
Thanks for letting us know.
We are currently working on this will update soon once done.

**Comment by mohamednajiullah** [comment]
Hi @mschmid 

Can you tell us, how you are using the google sheets option? 

When we tried to create a new Google sheet and use it, it seemed to work perfectly. So can you help us out with the following information

1. What URL are you entering in the text box?
2. Before creating the radar, did you publish the Google sheet using the 'Publish to the web' option?

Thanks,
Naji/Saran

**Comment by mschmid** [comment]
Thank both of you for the fast answer.
The given example works, if I paste the URL https://docs.google.com/spreadsheets/d/1waDG0_W3-yNiAaUfxcZhTKvl7AUCgXwQw8mdPjCz86U/edit#gid=0 on the website https://radar.thoughtworks.com the radar appears.
If however I copy the example sheet within google docs to be able to modify it and publish it: https://docs.google.com/spreadsheets/d/1CBKf8sCxbxg9RHJNFXd7o_au-9jzG96wi_QdFFbEqkk/edit#gid=0 the following message appears:

Oops! We can’t find the Google Sheet you’ve entered. Can you check the URL?
Please check FAQs for possible solutions.

**Comment by mschmid** [comment]
Hi @mohamednajiullah & @SARAN-thala, any news on that? Can you reproduce the error?

**Comment by SARAN-thala** [comment]
Hi @mschmid 

I also tried your scenario, this is my copy example sheet within google docs to be able to modify it and published it https://docs.google.com/spreadsheets/d/184npbFgA4dd5e28Inhm38KMk8HvcEEfpdTdiopkEyBc/edit#gid=0. If I paste this URL in https://radar.thoughtworks.com, the radar renders perfectly.

I would suggest to you, try with a new instance. This [doc](https://info.thoughtworks.com/visualize-your-tech-strategy-guide.html) might help you.

**Comment by arunvelsriram** [comment]
@mschmid your sheet is not "Published to web".

[https://spreadsheets.google.com/feeds/worksheets/1CBKf8sCxbxg9RHJNFXd7o_au-9jzG96wi_QdFFbEqkk/public/basic?alt=json&pli=1](https://spreadsheets.google.com/feeds/worksheets/1CBKf8sCxbxg9RHJNFXd7o_au-9jzG96wi_QdFFbEqkk/public/basic?alt=json&pli=1)

<img width="1103" alt="screen shot 2017-11-06 at 9 04 09 pm" src="https://user-images.githubusercontent.com/6568319/32448863-19ba44b4-c336-11e7-8767-4fbda0a5f59c.png">

Please refer Publish section of the doc @SARAN-thala mentioned.

**Comment by arunvelsriram** [comment]
FYI [https://spreadsheets.google.com/feeds/worksheets](https://spreadsheets.google.com/feeds/worksheets) returns `403` when the sheet is not "Published to the web".


It will be better if we handle this scenario gracefully by showing an appropriate message to users and direct them to this [doc](https://info.thoughtworks.com/visualize-your-tech-strategy-guide.html).

**Comment by mschmid** [comment]
@arunvelsriram Thank you vey much for the link with the spreadsheets - subdomain. This made the error visible. I published the document to the web, but I used another dialog (see screenshot) than the one that is described in the documentation.
<img width="544" alt="bildschirmfoto 2017-11-06 um 19 01 45" src="https://user-images.githubusercontent.com/468039/32456303-6d767ec6-c325-11e7-8087-b3f47e95b21d.png">

With the publishing via the right dialog it works
<img width="579" alt="bildschirmfoto 2017-11-06 um 19 05 59" src="https://user-images.githubusercontent.com/468039/32456378-a88bf2a2-c325-11e7-9697-e5fc90d73e62.png">

I was not aware that google has to different ways to publish a document into the public.

Thank you very much, now I am able to use this tool also!

**Comment by mohamednajiullah** [comment]
Thank you @arunvelsriram .  Considering this issue is resolved, I'll close this thread.

**Comment by mohamednajiullah** [comment]
Reopening this issue. We'll resolve this once we've gracefully handled this error.

**Comment by jcsonder** [comment]
> With the publishing via the right dialog it works

Hi @mschmid 

I have the same issue you had...
A question to your solution: How did you reach the _**right dialog**_? 😕

**Comment by jawn** [comment]
> Reopening this issue. We'll resolve this once we've gracefully handled this error.

Is this still on the, ahum, radar?

**Comment by arunvelsriram** [comment]
@mohamednajiullah is this resolved? If not, I can try to make a PR.

**Comment by sglebs** [comment]
Workaround: enable it with https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf/related?hl=en . A way simpler solution would be #231 .

**Comment by marisahoenig** [comment]
Closing as stale. Please reopen if it's not resolved.
