### ISSUE TITLE
Docker & Fedora 27

### ISSUE THREAD

**Issue by doribd** [thoughtworks/build-your-own-radar#43]
Hi 
Tried to run 'docker run -p 8080:8080 -v $PWD:/app -w /app -it node:7.3.0 /bin/sh -c 'npm install && npm run dev'' on fedora 27 without any previous installation of npm. Clean installation of fedora 27. 
Got an errors. 

npm ERR! Linux 4.13.9-200.fc26.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! path /app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log

Dor

**Comment by arunvelsriram** [comment]
Were you able to resolve this?

Looks like you're running `docker run -p 8080:8080 -v $PWD:/app -w /app -it node:7.3.0 /bin/sh -c 'npm install && npm run dev` from outside the project directory. Please check if your mount source points to the root of this project.

**Comment by arunvelsriram** [comment]
@doribd can we close this issue?

**Comment by doribd** [comment]
yes

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now
