### ISSUE TITLE
Is it possible to Change the tab Languages in the Webpage to Someother Name?

### ISSUE THREAD

**Issue by arjunm183** [thoughtworks/build-your-own-radar#46]
Hello Team,

Is it possible to Change the tab Languages in the webpage to someother Name?
If so kindly let me know since we have the data which represents someother field and not Languages.

Thanks and Regards,
Arjun.M

**Comment by mohamednajiullah** [comment]
Hello @arjunm183 

If you want to just change the 'Languages & Frameworks' text to something else, you can change it in the quadrant column in the google sheet. Just make sure to replace all occurrences of 'Languages & Frameworks' with the new quadrant name.

Thanks,
Digital Team

**Comment by arunvelsriram** [comment]
@arjunm183 does that answer your question? If, so we can close this issue.
