### ISSUE TITLE
Support for local Markdown files

### ISSUE THREAD

**Issue by rprieto** [thoughtworks/build-your-own-radar#47]
Thanks for open-sourcing the Radar!

What do you think about supporting local Markdown files as an input? Along with the `wwwthoughtworks/build-your-own-radar` Docker image, it would be a very simple way to get a Radar (or many radars) up. For example, I could setup a Git repo with:

```bash
.
|__ Dockerfile
|__ data
    |__ 2017-01
    |   |__ languages.md
    |   |__ platforms.md
    |   |__ tools.md
    |   |__ techniques.md
    |__ 2017-07
        |__ languages.md
        |__ platforms.md
        |__ tools.md
        |__ techniques.md
```

With the Dockerfile being a simple:

```dockerfile
FROM wwwthoughtworks/techradar
COPY data /data
```

Some of the advantages I can think of:
- easy to browse and view on Github
- easier to edit long HTML blip descriptions than in a spreadsheet
- supports pull-requests for updating the Radar, where you can even preview the HTML snippets

The Markdown files could look something like this:

---

# Languages and frameworks

## Python 3

| Ring  | New  |
|-------|------|
| Adopt | TRUE |

Python 3 introduced many useful features that are not backward compatible with Python 2.x. It also removed numerous Python 2.x features that were maintained for backward compatibility, making Python 3 easier to learn and use and more consistent with the rest of the language.

## Jest

| Ring  | New  |
|-------|------|
| Trial | TRUE |

Our teams are delighted with the results of using Jest for front-end testing. It provides a ‘zero-configuration’ experience and has out-of-the-box features such as mocking and code coverage. You can apply this testing framework not only to React applications, but also to other JavaScript frameworks. One of Jest's often hyped features is UI snapshot testing. Snapshot testing would be a good addition to the upper layer of the test pyramid, but remember, unit testing is still the solid foundation.

---

Another option is one Markdown file per blip, with a YAML front-matter to specify the quadrant / ring / status. This would be easier to parse but likely harder to maintain, compared to all blips in 1 file (for example trying to find an existing blip).

What do you think?

**Comment by miry** [comment]
Interested as well in any source like TSV,CSV or YAML

**Comment by Vaishnavij** [comment]
Hello @rprieto ,

We are closing this issue, as we have already merged a PR from @yzAlvin for using JSON as input.

Thanks,
Vaishnavi Jayakumar
BYOR Team
