### ISSUE TITLE
radar does not fit within browser window

### ISSUE THREAD

**Issue by adamwadesmith** [thoughtworks/build-your-own-radar#50]
The radar does not fit within the browser window at many aspect ratios.
Environment: Google Chrome 63 on Windows 10.
Data set: the sample data set provided at https://docs.google.com/spreadsheets/d/1waDG0_W3-yNiAaUfxcZhTKvl7AUCgXwQw8mdPjCz86U/edit#gid=0

Expected: the radar sizes itself so that content fits within the browser window.
Actual:
1. On the overview page, the bottom of the radar is cut off (see attachment).
2. On the quadrant page, the list of technologies underlaps the radar, and the radar is cut off at the bottom (see attachment).

![technology radar overview bug](https://user-images.githubusercontent.com/12560258/34918813-62b998aa-f927-11e7-8256-34509e17ef05.png)
![technology radar quadrant bug](https://user-images.githubusercontent.com/12560258/34918814-65c7bfe0-f927-11e7-9302-d0d38d88124e.png)

**Comment by marisahoenig** [comment]
With the new design refresh, this should no longer be an issue. Please open a new issue if it is.
