### ISSUE TITLE
Getting 403 Forbidden Error

### ISSUE THREAD

**Issue by MallikarjunKoguriReachLocal** [thoughtworks/build-your-own-radar#52]
After pulling and running the docker image, when I try to access it from browser as localhost:8080, i am getting 403 forbidden Error.

**Comment by DarrenRatcliffe** [comment]
Are you setting the environment variable for SERVER_NAMES as part of the run command?

docker run --rm -p 8080:80 -e SERVER_NAMES="localhost 127.0.0.1" wwwthoughtworks/build-your-own-radar

**Comment by marisahoenig** [comment]
Closing as stale. Please reopen if you're still having issues.

**Comment by marisahoenig** [comment]
Closing as stale
