### ISSUE TITLE
Build docker image with  Dockerfile Getting " Invalid Reference Format "

### ISSUE THREAD

**Issue by arjunm183** [thoughtworks/build-your-own-radar#57]
Hello Team,

When i try to Build the docker image with  the Dockerfile Getting " Invalid Reference Format " Error.

Sending build context to Docker daemon  1.262MB
Step 1/12 : FROM node:7.10.1 as source
invalid reference format

Thanks and Regards,
Arjun.M

**Comment by marisahoenig** [comment]
Closing as stale
