### ISSUE TITLE
Technology layout broken when too many in the list

### ISSUE THREAD

**Issue by yael-lorenzo** [thoughtworks/build-your-own-radar#59]
It is possible to see on the upper left side that the Framework list overlays the title of "infrastructure".

We also lost the "moved up and moved down" which in my opinion should be centered at the top of of the circle or at bottom.

I have been playing arround with the code but there are fixed offsets that mess all, not all is calculated. If I have time I will get this working and make a PR.

![tech-radar issue](https://user-images.githubusercontent.com/22622247/38911052-5b94789e-42ea-11e8-86e6-72ddd4564841.png)

**Comment by melissapalmer** [comment]
Hi @yael-lorenzo-olx  how are you getting the above view? I only see the graph/circle no text information when viewing the whole radar and not just one of the quadrants. 

![image](https://user-images.githubusercontent.com/6588511/51070347-7b15e680-1648-11e9-89c6-e9bacd87ccda.png)

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now

**Comment by marisahoenig** [comment]
Hi @yael-lorenzo — this issue has been fixed with the design refresh. Feel free to reopen this issue or create a new one if you're still having issues. Cheers 😊
