### ISSUE TITLE
Predefine order of the rings

### ISSUE THREAD

**Issue by pldupont** [thoughtworks/build-your-own-radar#6]
From what I saw, at the moment, the first ring correspond to the first value found. I would like a way to specify the ring order. The quadrant order would be nice too.

**Comment by NivedhaSenthil** [comment]
Hi @pldupont,

This is related to #1, we will update once fixed. We are trying to use the same order we give in the google sheet.

Thanks

**Comment by danielsiwiec** [comment]
+1 to @pldupont. I'd like the order to be predefined, too. I accidentally landed with hold -> trial -> adopt -> assess and to people unfamiliar with the radar it was a bit confusing

**Comment by rdoh** [comment]
Thanks @danielsiwiec. I agree; this and #1 are two manifestations of the same problem, so will close this as a duplicate. Please follow #1.
