### ISSUE TITLE
Status of this project? Which branch is viable?

### ISSUE THREAD

**Issue by BillAtSysco** [thoughtworks/build-your-own-radar#61]
Looking at this project I see a lot of contributions to the _release_ branch, from thoughtworks it seems, which has diverged significantly from _master_. I also see several PRs, some recent, which seem ready to be merged to _master_.

If I'm going to try to deploy this, which branch should I be using? 
Can I expect changes on _release_ to be merged with _master_ any time soon? Ever?

Some doc in the **README.md** or a **HOW_TO_CONTRIBUTE.md** might go a long way.

**Comment by BillAtSysco** [comment]
On closer inspection, it seems that _release_ and _master_ may have similar changes, but with completely different commits. _master_ has a greater number of commits than _release_ however. Attempting a merge seems to indicate that one is a QA branch. Is this accurate?

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now

**Comment by marisahoenig** [comment]
The _master_ branch is the main branch. Cheers!
