### ISSUE TITLE
How to edit the header "CSV" when rendering the radar

### ISSUE THREAD

**Issue by ab73863** [thoughtworks/build-your-own-radar#65]
Hello,

I was trying create my own radar by using an endpoint which spits out a csv content . The Radar is rendering well but the header of the Radar is always showing as CSV . How will I customize it to display my own radar name?

Kindly help...thank you.

Regards
Arun

**Comment by ab73863** [comment]
Found the way . :)
closing the issue.

**Comment by svdoever** [comment]
And what was "the way"? I only see a sheetId (url to csv file), sheetName is only used when using a Google Sheet...
