### ISSUE TITLE
Add Logos into the Radar

### ISSUE THREAD

**Issue by Pazze12** [thoughtworks/build-your-own-radar#77]
Hello,

I would like to add logos to the radar. I have created in sheet with 5 instead of 4 columns. In the fifth column I have inserted the links to my logos. Unfortunately I am very inexperienced. I want to see the small logo above the description. 

`<p><img src="my-logo-example,.jpg" style="width: 100px;height: 100px;"> <br><br>This is the description. You can use basic html such as the <strong>strong tag to emphasise keywords and phrases</strong> and insert <a href="https://www.thoughtworks.com">anchor links to documentation and referance material</a>.</p>`

Something like this - i made this in the browser html. But my dream is that when i add my google sheet the logos will come automated. I think its something in the radar.js but i am not sure.

**Comment by marisahoenig** [comment]
Hi @Pazze12 — unfortunately, we are not planning to add this feature to the BYOR tool. If you'd like to add images, we'd be happy to review a pull request.
Thank you!
