### ISSUE TITLE
Google OAuth does not work for protected sheets

### ISSUE THREAD

**Issue by evan-duncan** [thoughtworks/build-your-own-radar#79]
When you paste a URL for a protected sheet into the form and click "build my radar" you are presented a Google auth form. I click on the account that has access to the protected sheet, and I receive the error, "Sign in with Google temporarily disabled for this app".

![image](https://user-images.githubusercontent.com/5282872/53813548-80dec880-3f23-11e9-9998-e5b08aa0dc2c.png)

**Comment by viveksoundrapandi** [comment]
Hello @evan-duncan ,
    Thanks for pointing this out. It was working fine for a while and seems google has disabled the oauth as the verification is pending. We have submitted for verification and awaiting a confirmation from google. We will remove this feature until then and keep the issue open

**Comment by mohamednajiullah** [comment]
Hello @evan-duncan 

The app has been verified and redeployed. Thank you so much for pointing this out and helping us make BYOR better.

Thanks,
The BYOR Team
