### ISSUE TITLE
Intermittent (though frequent for us) error page

### ISSUE THREAD

**Issue by stephan42** [thoughtworks/build-your-own-radar#8]
About 40-60% of the time when hitting the radar URL, even with no recent changes to the underlying Google sheet, we will receive the standard "Oops page" (see below).  If you review your logs for yesterday, you will likely see the errors.  This can be reproduced by creating a sheet (seems to happen more often on larger documents - over 100 entries) and then pressing F5.  The radar page will alternate between showing the radar and sending the error.  During that time, no changes are being made to the sheet.  I though perhaps it was Google's syncing across servers, however, even an hour later with no changes to the sheet, this behavior continues.  I would be happy to share my Google sheet ID offline for you to replicate.  Note our Google sheet has a second tab, I will remove that tab and see if that resolves the issue.

We are loving this tool, thank you for building it!

_Oops! It seems like there are some problems with loading your data. Document is missing one or more required headers or they are misspelled. Check that your document contains headers for "name", "ring", "quadrant", "isNew", "description".
Please check FAQs for possible solutions._

**Comment by stephan42** [comment]
Removing the second tab seems to have made the page display much more reliable.  Note the second tab was never the active tab, it only contained meta-data.

**Comment by shahadarsh** [comment]
Yes I saw the same issue. It picks up sheet randomly when generating the radar. I raised a PR for the fix so it always looks at the 1st sheet. 
https://github.com/thoughtworks/build-your-own-radar/pull/12

**Comment by NivedhaSenthil** [comment]
Issue fixed by defaulting first sheet always. Merged pull PR  #12. Thanks @shahadarsh
