### ISSUE TITLE
Deploy built radar on own server

### ISSUE THREAD

**Issue by gustavz** [thoughtworks/build-your-own-radar#81]
I am new to web development so maybe this is a fairly easy one:

How do I deploy an own radar modified and built with this framework on a server?
I was thinking about something like Azure, but I am not bound to that.

Thanks in advance!

**Comment by viveksoundrapandi** [comment]
Hello @gustavz 
   If would like to deploy your own version, you can use our docker image and spin it up on any cloud provider and then make your  changes to the code. Closing it down as this is not an issue

**Comment by gustavz** [comment]
@viveksoundrapandi 
Thank you for your quick reply.
Can you also tell me how this deployment with docker on Azure would work?

**Comment by mohamednajiullah** [comment]
Hello @gustavz 

We have not worked on Azure but I believe you should be able to create a virtual machine (like EC2 on AWS), install docker and then pull the BYOR docker image from docker-hub and run it.

You can also use static site hosting to do it. You can do `npm run build` and copy the generated assets to an object storage that offers static site hosting (like S3 on AWS). That should also work.

Thanks,
The BYOR Team

**Comment by gustavz** [comment]
@mohamednajiullah perfect thank you!

**Comment by gustavz** [comment]
@mohamednajiullah 
I did a quick try of your second soltion and published the assets generated via `npm run build` to github pages site but it resulted in an empty page.

What could have gone wrong?

**Comment by mohamednajiullah** [comment]
Hi @gustavz 

What files did you copy to github pages? Also could you see if there was any console error in the browser while visiting the site?

**Comment by gustavz** [comment]
@mohamednajiullah I copied the files from the `/dist` folder generated by `npm run build` to a github pages website.

The console error is the following (german):
```
Laden fehlgeschlagen für das <script> mit der Quelle "https://www.googletagmanager.com/gtm.js?id=GTM-P97X8B". techradar:1:1
Laden fehlgeschlagen für das <script> mit der Quelle "https://cc-github.bmwgroup.net/main.e3c97d87deda566a821f.js".
```

**Comment by mohamednajiullah** [comment]
Hello @gustavz 

These errors have nothing to do with the radar not working. If you have hosted it somewhere can you give us a link?

One more thing that you can try is to check all the resources that are referred to in the files. Usually the static radar files are supposed to be hosted on a storage service like S3. If they are used on a standalone system then doing the following makes it work

1. Make sure all `link` tags `href` attribute does not have a `/` prefixing the file name.
2. Make sure all `script` tags `src` attribute does not have a `/` prefixing the file name.
3. Make sure all references to images do not have a `/` prefix (Find all instances of `\images\` and remove the prefix `\` .

Hope this helps!

**Comment by gustavz** [comment]
@mohamednajiullah Thanks for your quick reply!
Does this also include all absolute `require` paths and the ones starting with `.\` ?
