### ISSUE TITLE
radar does not get build when running local

### ISSUE THREAD

**Issue by gustavz** [thoughtworks/build-your-own-radar#84]
Locally Running 
```
npm install
npm run dev
```
and visiting 
```
http://localhost:8080/
```
and pasting in any google sheet that works with the default thoughtworks BYOR site, 
it hangs forever with the screen saying:
```
Building your radar...

Your Technology Radar will be available in just a few seconds
```

>Note: this happens on the master branch without any changes

**Comment by gustavz** [comment]
any hints on this @mohamednajiullah ?

**Comment by mohamednajiullah** [comment]
Hello @gustavz 

We tried running it locally and it worked fine. Could you please post what error you receive in the browser console to help us? And also if possible the file that you used while running it locally?

(P.S Also try doing a `npm i` just in case)

Thanks,
The BYOR team

**Comment by gustavz** [comment]
Hi @mohamednajiullah 

The datasheet i am using for testing is:
https://docs.google.com/spreadsheets/d/1Hq2jTUTqHjImPZDPan5XcKbclv9ibmQhwBDv7GsAFKQ/edit#gid=0
but I also use your default Nov'15 Sheet:
https://docs.google.com/spreadsheets/d/1YXkrgV7Y6zShiPeyw4Y5_19QOfu5I6CyH5sGnbkEyiI/edit#gid=0

**Both** sheets work with your default radar builder:
https://radar.thoughtworks.com/

But with a clone of the radar only the default sheet works (running local or on azure blobs).

What could be the reason?

**Comment by gustavz** [comment]
Hi @mohamednajiullah 
I see the following error:
```
login https://XXX/main.d9fa0c6e0a5fb57d54a3.js:322
    authenticate https://XXX/main.d9fa0c6e0a5fb57d54a3.js:161
    initClient https://XXX/main.d9fa0c6e0a5fb57d54a3.js:322
    r2 https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.VtBTz4iwQTU.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO2a-4GBdY-a4raOb0FDWrDtWL8jw/cb=gapi.loaded_0:120
    xs https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.VtBTz4iwQTU.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO2a-4GBdY-a4raOb0FDWrDtWL8jw/cb=gapi.loaded_0:123
    Wq https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.VtBTz4iwQTU.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO2a-4GBdY-a4raOb0FDWrDtWL8jw/cb=gapi.loaded_0:123
    uea https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.VtBTz4iwQTU.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO2a-4GBdY-a4raOb0FDWrDtWL8jw/cb=gapi.loaded_0:123
    Ap https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.de.VtBTz4iwQTU.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=wQ/rs=AGLTcCO2a-4GBdY-a4raOb0FDWrDtWL8jw/cb=gapi.loaded_0:115
```

**Comment by gustavz** [comment]
Furthermore this warning:
`Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://accounts.google.com/ServiceLogin?service=wise&passive=1209600&continue=https://spreadsheets.google.com/feeds/worksheets/1Hq2jTUTqHjImPZDPan5XcKbclv9ibmQhwBDv7GsAFKQ/public/basic?alt%3Djson&followup=https://spreadsheets.google.com/feeds/worksheets/1Hq2jTUTqHjImPZDPan5XcKbclv9ibmQhwBDv7GsAFKQ/public/basic?alt%3Djson&ltmpl=sheets. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).[Weitere Informationen]`

**Comment by gustavz** [comment]
solved this with https://github.com/thoughtworks/build-your-own-radar/issues/66
