### ISSUE TITLE
Tech Radar is not compatible with IE 11

### ISSUE THREAD

**Issue by bharathnatarajan1** [thoughtworks/build-your-own-radar#90]
Getting a blank page when trying to access Tech Radar using IE 11, it works fine with chrome and firefox.

O.S.: Windows 7

**Comment by muddasani** [comment]
I have the same issue with Safari (10.1.2) browser.

**Comment by m1ke-RSG** [comment]
i have submitted a pull request that adds babel transpiling for IE11 and newer browsers and as well as adding additional options to for the radar creation.
https://github.com/thoughtworks/build-your-own-radar/pull/99

or if it doesnt get submitted you can use our fork instead: https://github.com/raiffeisensoftware/build-your-own-radar

**Comment by bharathnatarajan1** [comment]
@m1ke-RSG  Thank you very much. Will apply your code fix.

**Comment by bharathnatarajan1** [comment]
@m1ke-RSG Thank you for the fix.

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now
