### ISSUE TITLE
Problem with CSV file and changing name of the radar

### ISSUE THREAD

**Issue by ChaitanyaSaravate** [thoughtworks/build-your-own-radar#91]
Hello,

I am building radar for my team. Due to company policy, we cannot use Google Drive. But my tech radar worked well with google spreadsheet when I tried with it.

So CSV is the option for me. I tried to use local CSV file but it did not work. 
I then hosted it under the GIT project in TFS and gave TFS GIT URL but that too does not work. It neither works nor does it give any error. 
Then I hosted in my own GitHub account to try out that option too; but it too did not work due to CORS policy. 

**What I need to do to get it working for CSV? What other options I have apart from CSV and Google Spreadsheet?**

Second question: **What I need to do to add my company or team name to the radar?**

**Comment by parthparulekar** [comment]
To include the company or team names, you can add images and favicons to the UI itself similar to how the ThoughtWorks logos are already being implemented. As for adding a name/image to the circular radar object itself, I do not know, but I don't think it is optimized to hold more text like that.

**Comment by marisahoenig** [comment]
@ChaitanyaSaravate — I would recommend forking the repo and adding you CSV file into the repo or to run this repo locally and reference your CSV from another repo. The BYOR tool should work with your CSV.

As @parthparulekar suggested, I would recommend replacing the Thoughtworks logo on your local version if that's how you want to customize it.

Closing this issue as I don't see any immediate needs. Please reopen if you're still having issues.
