### ISSUE TITLE
Is there way to search and retrieve a blip that once featured in radar

### ISSUE THREAD

**Issue by bharathnatarajan1** [thoughtworks/build-your-own-radar#93]
Is there way to search and retrieve a blip that once featured in radar for self-hosted tech radar?

Something like the functionality in thoughworks radar at https://www.thoughtworks.com/radar/a-z

**Comment by viveksoundrapandi** [comment]
@bharathnatarajan1 currently the functioanlity is not available, as the way the radar works is based on the context of current sheet only

**Comment by bharathnatarajan1** [comment]
@viveksoundrapandi thank you for the response.
