### ISSUE TITLE
Tech Radar is broken on Safari browser

### ISSUE THREAD

**Issue by muddasani** [thoughtworks/build-your-own-radar#94]
Tech Radar works fine with Chrome and Firefox. But doesn't work on Safari (version 10.1.2). It just displays a blank page.

**Comment by m1ke-RSG** [comment]
i have submitted a pullrequest that fixes this and more other issues as well as adding additional options.
https://github.com/thoughtworks/build-your-own-radar/pull/99

or if it doesnt get submitted you can use our fork instead: https://github.com/raiffeisensoftware/build-your-own-radar

**Comment by setchy** [comment]
@devansh-sharma-tw this should be able to be closed now

**Comment by marisahoenig** [comment]
Thank you, @setchy!
