### ISSUE TITLE
XMLHttpRequest chokes with HTTP response code 500 

### ISSUE THREAD

**Issue by micheldrescher** [thoughtworks/build-your-own-radar#98]
Hi,

Today I wanted to further code around, and came across a very annoying issue as follows:

Nothing changed, neither code, underpinning Google spreadsheet, or anything else. I was able to use the system yesterday without any issues.

Yet, today, the radar chokes with  a HTTP response code 500 as a result of an attempted HMHttpRequest to fetch the published Google spredsheet.

The affected code is in /src/util/sheet.js, in function Sheet.self.validate:
```javascript
  self.validate = function (callback) {
    var feedURL = 'https://spreadsheets.google.com/feeds/worksheets/' + self.id + '/public/basic?alt=json'

    // TODO: Move this out (as HTTPClient)
    var xhr = new XMLHttpRequest()
    xhr.open('GET', feedURL, true)
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {
        if (xhr.status === 200) {
          return callback()
        } else if (xhr.status === 404) {
          return callback(new SheetNotFoundError(ExceptionMessages.SHEET_NOT_FOUND))
        } else {
          return callback(new UnauthorizedError(ExceptionMessages.UNAUTHORIZED))
        }
      }
    }
    xhr.send(null)
  }
```

Specifically, it quits at returning at the last line (i.e. "xhr.send(null)")

Attached is a screenshot with Chrome's console showing what's going on, including some cmd line debugging of the XML request state.

![Screenshot 2019-04-30 at 09 53 28](https://user-images.githubusercontent.com/25902030/56950713-077fe280-6b2e-11e9-82d1-2f4c00d396c9.png)

A quick look at https://www.w3schools.com/js/js_ajax_http.asp reveals that apparently the XML document must be located in the same domain where the request comes from - which is not true for the radar using remote Google sheets. Did Google now enforce this policy on their Google spreadsheet service?

Further digging, I came across CORS designed to allow sharing resources across domains: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for an in-depth analysis and specifically https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Examples_of_access_control_scenarios discussing conditions of CORS not being triggered

Did anyone come across the same issue?

This is pretty much a dealbreaker for me as we are a collaborative project relying on Google Sheets for streamlined data sharing for the Technology Radar!

Thanks,
Michel

**Comment by muddasani** [comment]
I am facing the same issue.

**Comment by micheldrescher** [comment]
Some more digging in the Javascript console reveals that apparently this is now trapped in the CORS enforcing by Google - at least as far as I can see in the following request and response headers for the offending call. See screenshots below.

Any help/hints on this? I consider this CRITICAL as it completely breaks the fundamental use case of visualising data in a shared Google spreadsheet!

Thanks,
Michel

The request to the (localhost server) to fetch the Google Spreadsheet:
![Screenshot 2019-04-30 at 10 27 20](https://user-images.githubusercontent.com/25902030/56952709-d6ee7780-6b32-11e9-9626-64dcd4257d3c.png)

The Response headers as set by the localhost Tech Radar server (I think):
![Screenshot 2019-04-30 at 10 30 34](https://user-images.githubusercontent.com/25902030/56952801-0bfaca00-6b33-11e9-986d-62bfbe93841e.png)

And finally the core response
![Screenshot 2019-04-30 at 10 31 39](https://user-images.githubusercontent.com/25902030/56952896-35b3f100-6b33-11e9-8898-181e3ba64165.png)

IP address 216.58.208.142 resolves to Google in Mountain View, California.

**Comment by micheldrescher** [comment]
Whatever it was, it seems fixed now - Google, shame on you! ;-)
